import { calculateEconomics,confidenceFor } from './economics'
import type { BuyerCap,DataFreshness,ExperimentVariant,LeadAttribution,MediaCampaign,MediaDailyMetric,Recommendation } from '../types'

export interface AcquisitionMetrics { impressions:number;clicks:number;spend:number|null;platformConversions:number;leads:number;validatedLeads:number;acceptedLeads:number;qualifiedOutcomes:number;applicationsSales:number;downstreamConversions:number;startsCompletions:number;rejectedLeads:number;recoverableLeads:number;recoveredLeads:number;recoveredRevenue:number|null;revenue:number|null;deliveryCost:number|null;ctr:number|null;cpc:number|null;cpm:number|null;platformConversionRate:number|null;leadConversionRate:number|null;acceptanceRate:number|null;downstreamConversionRate:number|null;recoveryRate:number|null;costPerLead:number|null;costPerAcceptedLead:number|null;revenuePerLead:number|null;contribution:number|null;contributionPerLead:number|null }
const sumNullable=(rows:(number|null)[])=>rows.some((row)=>row!=null)?rows.reduce<number>((sum,row)=>sum+(row??0),0):null
const divide=(n:number|null,d:number)=>n==null||d<=0?null:Number((n/d).toFixed(2))
export function aggregateAcquisition(rows:MediaDailyMetric[]):AcquisitionMetrics{const totals={impressions:0,clicks:0,platformConversions:0,leads:0,validatedLeads:0,acceptedLeads:0,qualifiedOutcomes:0,applicationsSales:0,downstreamConversions:0,startsCompletions:0,rejectedLeads:0,recoverableLeads:0,recoveredLeads:0};for(const row of rows)for(const key of Object.keys(totals) as (keyof typeof totals)[])totals[key]+=row[key];const spend=sumNullable(rows.map((row)=>row.spend));const revenue=sumNullable(rows.map((row)=>row.revenue));const recoveredRevenue=sumNullable(rows.map((row)=>row.recoveredRevenue));const deliveryCost=sumNullable(rows.map((row)=>row.deliveryCost));const economics=calculateEconomics({leads:totals.leads,accepted:totals.acceptedLeads,qualified:totals.qualifiedOutcomes,applicationsSales:totals.applicationsSales,conversions:totals.downstreamConversions,startsCompletions:totals.startsCompletions,spend,revenue,recoveryRevenue:recoveredRevenue,deliveryCost});return {...totals,spend,revenue,recoveredRevenue,deliveryCost,ctr:divide(totals.clicks*100,totals.impressions),cpc:divide(spend,totals.clicks),cpm:divide(spend==null?null:spend*1000,totals.impressions),platformConversionRate:divide(totals.platformConversions*100,totals.clicks),leadConversionRate:divide(totals.leads*100,totals.clicks),acceptanceRate:divide(totals.acceptedLeads*100,totals.leads),downstreamConversionRate:divide(totals.downstreamConversions*100,totals.leads),recoveryRate:divide(totals.recoveredLeads*100,totals.recoverableLeads),costPerLead:economics.costPerLead,costPerAcceptedLead:economics.costPerAcceptedLead,revenuePerLead:economics.revenuePerLead,contribution:economics.grossContribution,contributionPerLead:economics.contributionPerLead}}
export interface ScorecardRow { id:string;name:string;platform:string;metrics:AcquisitionMetrics }
export function scorecard(metrics:MediaDailyMetric[],dimension:'account'|'campaign'|'ad_group'|'creative',labels:Map<string,{name:string;platform:string}>):ScorecardRow[]{const key=(row:MediaDailyMetric)=>dimension==='account'?row.mediaAccountId:dimension==='campaign'?row.mediaCampaignId:dimension==='ad_group'?row.mediaAdGroupId:row.mediaCreativeId;const groups=new Map<string,MediaDailyMetric[]>();for(const row of metrics){const id=key(row);if(!id)continue;groups.set(id,[...(groups.get(id)??[]),row])}return [...groups].map(([id,rows])=>({id,name:labels.get(id)?.name??'Unknown',platform:labels.get(id)?.platform??'Unknown',metrics:aggregateAcquisition(rows)}))}
export interface FatigueSignal { creativeId:string;status:'healthy'|'watch'|'fatiguing';ctrChange:number|null;cpcChange:number|null;frequencyChange:number|null;explanation:string }
export function detectCreativeFatigue(creativeId:string,current:MediaDailyMetric[],prior:MediaDailyMetric[],threshold=15):FatigueSignal{const a=aggregateAcquisition(current),b=aggregateAcquisition(prior);const change=(now:number|null,before:number|null)=>now==null||before==null||before===0?null:Number(((now-before)/Math.abs(before)*100).toFixed(1));const ctrChange=change(a.ctr,b.ctr),cpcChange=change(a.cpc,b.cpc),frequencyChange=change(current.at(-1)?.frequency??null,prior.at(-1)?.frequency??null);const declining=(ctrChange!=null&&ctrChange<=-threshold?1:0)+(cpcChange!=null&&cpcChange>=threshold?1:0)+(frequencyChange!=null&&frequencyChange>=threshold?1:0);return {creativeId,status:declining>=2?'fatiguing':declining===1?'watch':'healthy',ctrChange,cpcChange,frequencyChange,explanation:declining>=2?'CTR, CPC, or frequency crossed deterministic fatigue thresholds.':'No paired fatigue signals crossed the configured threshold.'}}
export function resolveLastKnownTouch(tenantId:string,leadId:string,touches:LeadAttribution[]){return touches.filter((row)=>row.tenantId===tenantId&&row.leadId===leadId).sort((a,b)=>b.attributedAt.localeCompare(a.attributedAt))[0]??null}
export function evaluateExperiment(variants:ExperimentVariant[],minimumSampleSize:number,freshness:DataFreshness='fresh'){const rows=variants.map((variant)=>({variant,confidence:confidenceFor(variant.visitors??variant.leads,minimumSampleSize,minimumSampleSize*3,freshness),leadRate:divide(variant.leads*100,variant.visitors??0),acceptanceRate:divide(variant.acceptedLeads*100,variant.leads),conversionRate:divide(variant.downstreamConversions*100,variant.leads),revenuePerVisitor:divide(variant.revenue,variant.visitors??0),contributionPerVisitor:divide(variant.contribution,variant.visitors??0)}));const eligible=rows.filter((row)=>(row.variant.visitors??row.variant.leads)>=minimumSampleSize&&row.contributionPerVisitor!=null);const winner=eligible.length>=2?[...eligible].sort((a,b)=>(b.contributionPerVisitor??-Infinity)-(a.contributionPerVisitor??-Infinity))[0]:null;return {rows,winner:winner?.variant.id??null,insufficientSample:eligible.length<2}}
export function capacityContext(campaign:MediaCampaign,caps:BuyerCap[],now=new Date()){const relevant=caps.filter((cap)=>cap.programId===campaign.programId&&cap.status==='active');const remaining=relevant.reduce((sum,cap)=>sum+Math.max(0,cap.limit-cap.delivered),0);const days=relevant.length?Math.max(0,(Math.min(...relevant.map((cap)=>Date.parse(cap.periodEnd)))-now.getTime())/86_400_000):null;return {remaining,days,constrained:relevant.length>0&&remaining<50}}
export function acquisitionRecommendations(tenantId:string,campaignRows:ScorecardRow[],fatigue:FatigueSignal[],freshness:DataFreshness,generatedAt:string):Recommendation[]{const base=(id:string,type:'campaign'|'creative',title:string,summary:string,evidence:string[],sampleSize:number):Recommendation=>({id,tenantId,recommendationType:type,title,summary,status:'new',priority:'high',confidence:confidenceFor(sampleSize,30,100,freshness),sampleSize,evidence,estimatedImpact:{potentialContribution:null},relatedBuyerId:null,relatedProgramId:null,relatedCampaignId:type==='campaign'?id.replace('acq-rec-campaign-',''):null,relatedLeadId:null,freshness,freshnessWarning:freshness==='fresh'?null:`Media evidence is ${freshness}; refresh before acting.`,generatedAt,expiresAt:new Date(Date.parse(generatedAt)+14*86_400_000).toISOString(),createdAt:generatedAt,updatedAt:generatedAt});const result:Recommendation[]=[];const valuable=[...campaignRows].filter((row)=>row.metrics.costPerLead!=null&&row.metrics.contributionPerLead!=null).sort((a,b)=>(b.metrics.contributionPerLead??-Infinity)-(a.metrics.contributionPerLead??-Infinity))[0];if(valuable)result.push(base(`acq-rec-campaign-${valuable.id}`,'campaign','Preserve downstream campaign value',`${valuable.name} leads should be judged by contribution, not CPL alone.`,[`CPL: ${valuable.metrics.costPerLead}.`,`Contribution per lead: ${valuable.metrics.contributionPerLead}.`],valuable.metrics.leads));for(const item of fatigue.filter((row)=>row.status==='fatiguing'))result.push(base(`acq-rec-creative-${item.creativeId}`,'creative','Review creative fatigue','Review replacement or refresh; no budget or media change will occur automatically.',[`CTR change: ${item.ctrChange}%.`,`CPC change: ${item.cpcChange}%.`],30));return result}
export function acquisitionPayloadHasPII(payload:unknown){return /email|phone|first_name|last_name|address|full_name/i.test(JSON.stringify(payload))}
