import type { ConfidenceLevel,DataFreshness,OptimizationAnomaly,Recommendation,RecommendationPriority } from '../types'
import { confidenceFor } from './economics'

export interface AnomalyInput { tenantId:string;metricKey:string;current:number;baseline:number;sampleSize:number;thresholdPercent:number;direction?:'increase'|'decrease'|'both';dimensionType?:string;dimensionId?:string|null;likelyDriver?:string|null }
export function detectAnomaly(input:AnomalyInput):OptimizationAnomaly|null{if(input.baseline===0)return null;const change=(input.current-input.baseline)/Math.abs(input.baseline)*100;const direction=input.direction??'both';if(Math.abs(change)<input.thresholdPercent||(direction==='increase'&&change<0)||(direction==='decrease'&&change>0))return null;const severity:RecommendationPriority=Math.abs(change)>=input.thresholdPercent*2?'high':'medium';const confidence=confidenceFor(input.sampleSize,20,100);return {id:`anomaly-${input.metricKey}-${input.dimensionId??'tenant'}`,tenantId:input.tenantId,metricKey:input.metricKey,dimensionType:input.dimensionType??'tenant',dimensionId:input.dimensionId??null,status:'active',severity,currentValue:input.current,baselineValue:input.baseline,changePercent:Number(change.toFixed(1)),threshold:input.thresholdPercent,confidence,sampleSize:input.sampleSize,likelyDriver:input.likelyDriver??null,safeExplanation:`${input.metricKey.replaceAll('_',' ')} changed ${Math.abs(change).toFixed(1)}% versus its trailing baseline.`,detectedAt:new Date().toISOString(),resolvedAt:null}}

export interface SanitizedOptimizationContext { tenantId:string;generatedAt:string;freshness:DataFreshness;metrics:Record<string,number|null>;pacing:{buyerId:string;programId:string|null;status:string;remaining:number;currentPace:number;requiredPace:number}[];anomalies:{metricKey:string;severity:string;changePercent:number|null;likelyDriver:string|null}[] }
export interface RecommendationProvider { generate(context:SanitizedOptimizationContext):Recommendation[] }
const recommendation=(context:SanitizedOptimizationContext,id:string,title:string,summary:string,type:Recommendation['recommendationType'],priority:RecommendationPriority,confidence:ConfidenceLevel,evidence:string[],impact:Record<string,number|null>,relations:Partial<Pick<Recommendation,'relatedBuyerId'|'relatedProgramId'|'relatedCampaignId'>>={}):Recommendation=>({id,tenantId:context.tenantId,recommendationType:type,title,summary,status:'new',priority,confidence,sampleSize:Number(context.metrics.sampleSize??0),evidence,estimatedImpact:impact,relatedBuyerId:relations.relatedBuyerId??null,relatedProgramId:relations.relatedProgramId??null,relatedCampaignId:relations.relatedCampaignId??null,relatedLeadId:null,freshness:context.freshness,freshnessWarning:context.freshness==='fresh'?null:`Confidence reduced because dependent data is ${context.freshness}.`,generatedAt:context.generatedAt,expiresAt:new Date(Date.parse(context.generatedAt)+14*86_400_000).toISOString(),createdAt:context.generatedAt,updatedAt:context.generatedAt})

export class DeterministicRecommendationProvider implements RecommendationProvider{
  generate(context:SanitizedOptimizationContext){const rows:Recommendation[]=[];for(const pace of context.pacing){if(pace.status==='projected_early_cap'||pace.status==='over_pace')rows.push(recommendation(context,`rec-cap-${pace.buyerId}`, 'Buyer capacity is projected to tighten early','Request additional approved allocation or shift incremental eligible volume.','capacity','high',context.freshness==='fresh'?'high':'medium',[`Current pace: ${pace.currentPace}/day.`,`Required pace: ${pace.requiredPace}/day.`,`Remaining capacity: ${pace.remaining}.`],{potentialCapRiskAvoided:pace.remaining},{relatedBuyerId:pace.buyerId,relatedProgramId:pace.programId}))}
    for(const anomaly of context.anomalies)rows.push(recommendation(context,`rec-anomaly-${anomaly.metricKey}` ,`${anomaly.metricKey.replaceAll('_',' ')} requires review`,anomaly.likelyDriver?`Review the identified driver: ${anomaly.likelyDriver}.`:'Primary driver not yet identified.',anomaly.metricKey.includes('response')?'buyer':'data_quality',anomaly.severity as RecommendationPriority,context.freshness==='stale'?'low':'medium',[`Change versus baseline: ${anomaly.changePercent??0}%.`,anomaly.likelyDriver?`Likely driver: ${anomaly.likelyDriver}.`:'Primary driver not yet identified.'],{potentialLeadsPreserved:null}))
    return rows}
}
export class FutureAIRecommendationProvider implements RecommendationProvider{generate():Recommendation[]{throw new Error('No external AI provider is configured.')}}
export function isExpired(recommendation:Recommendation,now=new Date()){return Boolean(recommendation.expiresAt&&Date.parse(recommendation.expiresAt)<=now.getTime())}
export function sanitizedContextHasPII(context:SanitizedOptimizationContext){return /email|phone|first_name|last_name|address|auth|token|secret/i.test(JSON.stringify(context))}
