import { release7Demo } from '../data/release7Demo'
import { parseCsv } from '../integrations/csv'
import { googleAdsAdapter } from '../integrations/media/googleAdsAdapter'
import { metaAdapter } from '../integrations/media/metaAdapter'
import { mediaMetricIdempotencyKey } from '../integrations/media/mediaConnector'
import { tiktokAdapter } from '../integrations/media/tiktokAdapter'
import type { MediaImportIssue,MediaNormalizationResult } from '../integrations/media/types'
import { acquisitionRecommendations,aggregateAcquisition,capacityContext,detectCreativeFatigue,evaluateExperiment,scorecard,type ScorecardRow } from '../lib/acquisition'
import { demoMode,supabase } from '../lib/supabase'
import type { BuyerCap,DataFreshness,Experiment,ExperimentVariant,IntegrationFieldMapping,LandingPage,LeadAttribution,MediaAccount,MediaAd,MediaAdGroup,MediaCampaign,MediaCreative,MediaDailyMetric,MediaPlatform,MediaSyncRun,Recommendation } from '../types'

export interface AcquisitionWorkspace { accounts:MediaAccount[];campaigns:MediaCampaign[];adGroups:MediaAdGroup[];ads:MediaAd[];creatives:MediaCreative[];metrics:MediaDailyMetric[];syncRuns:MediaSyncRun[];landingPages:LandingPage[];attributions:LeadAttribution[];experiments:Experiment[];experimentVariants:ExperimentVariant[];mappings:IntegrationFieldMapping[] }
export interface MediaImportPreview { rowsDetected:number;validRows:number;invalidRows:number;duplicates:number;rows:{rowNumber:number;result:MediaNormalizationResult;idempotencyKey:string|null}[] }
export interface AcquisitionReport { totals:ReturnType<typeof aggregateAcquisition>;sources:ScorecardRow[];campaigns:ScorecardRow[];adGroups:ScorecardRow[];creatives:ScorecardRow[];fatigue:ReturnType<typeof detectCreativeFatigue>[];freshness:DataFreshness;freshnessWarning:string|null;programs:{programId:string;metrics:ReturnType<typeof aggregateAcquisition>}[];capacity:{campaign:MediaCampaign;context:ReturnType<typeof capacityContext>}[];experiments:{experiment:Experiment;result:ReturnType<typeof evaluateExperiment>}[];recommendations:Recommendation[] }
const scope=<T extends {tenantId:string}>(rows:T[],tenantId:string)=>structuredClone(rows.filter((row)=>row.tenantId===tenantId))
const camel=(value:string)=>value.replace(/_([a-z])/g,(_,letter:string)=>letter.toUpperCase())
function mapped<T>(result:{data:Record<string,unknown>[]|null;error:{message:string}|null}):T[]{if(result.error)throw new Error(result.error.message);return (result.data??[]).map((row)=>Object.fromEntries(Object.entries(row).map(([key,value])=>[camel(key),value])) as T)}
const adapters={meta:metaAdapter,google_ads:googleAdsAdapter,tiktok:tiktokAdapter}

export function previewMediaImport(csv:string,platform:MediaPlatform,mappings:IntegrationFieldMapping[],existing:MediaDailyMetric[]):MediaImportPreview{if(new Blob([csv]).size>5_000_000)throw new Error('Files larger than 5 MB require the trusted background import service.');const normalized=adapters[platform].normalize(parseCsv(csv),mappings);const existingKeys=new Set(existing.map((row)=>[platform,row.mediaAccountId,row.mediaCampaignId??'-',row.mediaAdGroupId??'-',row.mediaAdId??'-',row.metricDate].join(':')));const rows=normalized.map((result,index)=>{const key=result.record?mediaMetricIdempotencyKey(result.record):null;const duplicate=key?existingKeys.has(key):false;const issues:MediaImportIssue[]=duplicate?[...result.issues,{code:'DUPLICATE_METRIC',message:'This platform entity and date already exist.',severity:'warning'}]:result.issues;return {rowNumber:index+2,result:{...result,issues},idempotencyKey:key}});return {rowsDetected:rows.length,validRows:rows.filter((row)=>row.result.record&&!row.result.issues.some((issue)=>issue.severity==='error')).length,invalidRows:rows.filter((row)=>!row.result.record||row.result.issues.some((issue)=>issue.severity==='error')).length,duplicates:rows.filter((row)=>row.result.issues.some((issue)=>issue.code==='DUPLICATE_METRIC')).length,rows}}

function report(workspace:AcquisitionWorkspace,caps:BuyerCap[],now=new Date()):AcquisitionReport{const accountLabels=new Map(workspace.accounts.map((row)=>[row.id,{name:row.displayName,platform:row.platform.replace('_ads','')}]))
  const campaignLabels=new Map(workspace.campaigns.map((row)=>[row.id,{name:row.name,platform:row.platform.replace('_ads','')}]))
  const adGroupLabels=new Map(workspace.adGroups.map((row)=>{const campaign=workspace.campaigns.find((item)=>item.id===row.mediaCampaignId);return [row.id,{name:row.name,platform:campaign?.platform.replace('_ads','')??'Unknown'}]}))
  const creativeLabels=new Map(workspace.creatives.map((row)=>[row.id,{name:row.name,platform:row.platform.replace('_ads','')}]))
  const sources=scorecard(workspace.metrics,'account',accountLabels),campaignRows=scorecard(workspace.metrics,'campaign',campaignLabels),adGroups=scorecard(workspace.metrics,'ad_group',adGroupLabels),creatives=scorecard(workspace.metrics,'creative',creativeLabels)
  const dates=[...new Set(workspace.metrics.map((row)=>row.metricDate))].sort();const split=dates[Math.max(0,dates.length-7)];const fatigue=workspace.creatives.map((creative)=>detectCreativeFatigue(creative.id,workspace.metrics.filter((row)=>row.mediaCreativeId===creative.id&&row.metricDate>=split),workspace.metrics.filter((row)=>row.mediaCreativeId===creative.id&&row.metricDate<split)))
  const connected=workspace.accounts.filter((row)=>row.status==='connected');const timestamps=connected.map((row)=>row.lastSyncAt?Date.parse(row.lastSyncAt):0).filter(Boolean);const age=timestamps.length?(now.getTime()-Math.min(...timestamps))/3_600_000:null;const freshness:DataFreshness=age==null?'unknown':age>24?'stale':age>6?'delayed':'fresh';const freshnessWarning=freshness==='fresh'?null:`Acquisition data is ${freshness}; refresh media evidence before changing spend.`
  const programs=[...new Set(workspace.campaigns.map((row)=>row.programId).filter(Boolean) as string[])].map((programId)=>{const ids=new Set(workspace.campaigns.filter((row)=>row.programId===programId).map((row)=>row.id));return {programId,metrics:aggregateAcquisition(workspace.metrics.filter((row)=>row.mediaCampaignId&&ids.has(row.mediaCampaignId)))}})
  const capacity=workspace.campaigns.map((campaign)=>({campaign,context:capacityContext(campaign,caps,now)}));const experiments=workspace.experiments.map((experiment)=>({experiment,result:evaluateExperiment(workspace.experimentVariants.filter((row)=>row.experimentId===experiment.id),experiment.minimumSampleSize,freshness)}));const recommendations=acquisitionRecommendations(workspace.accounts[0]?.tenantId??'',campaignRows,fatigue,freshness,now.toISOString())
  return {totals:aggregateAcquisition(workspace.metrics),sources,campaigns:campaignRows,adGroups,creatives,fatigue,freshness,freshnessWarning,programs,capacity,experiments,recommendations}}

export const acquisitionService={report,
  async getWorkspace(tenantId:string):Promise<AcquisitionWorkspace>{if(demoMode)return {accounts:scope(release7Demo.accounts,tenantId),campaigns:scope(release7Demo.campaigns,tenantId),adGroups:scope(release7Demo.adGroups,tenantId),ads:scope(release7Demo.ads,tenantId),creatives:scope(release7Demo.creatives,tenantId),metrics:scope(release7Demo.metrics,tenantId),syncRuns:scope(release7Demo.syncRuns,tenantId),landingPages:scope(release7Demo.landingPages,tenantId),attributions:scope(release7Demo.attributions,tenantId),experiments:scope(release7Demo.experiments,tenantId),experimentVariants:scope(release7Demo.experimentVariants,tenantId),mappings:[]};if(!supabase)throw new Error('Supabase is not configured.');const results=await Promise.all([supabase.from('media_accounts').select('*').eq('tenant_id',tenantId),supabase.from('media_campaigns').select('*').eq('tenant_id',tenantId),supabase.from('media_ad_groups').select('*').eq('tenant_id',tenantId),supabase.from('media_ads').select('*').eq('tenant_id',tenantId),supabase.from('media_creatives').select('*').eq('tenant_id',tenantId),supabase.from('media_daily_metrics').select('*').eq('tenant_id',tenantId).order('metric_date'),supabase.from('media_sync_runs').select('*').eq('tenant_id',tenantId).order('started_at',{ascending:false}),supabase.from('landing_pages').select('*').eq('tenant_id',tenantId),supabase.from('lead_acquisition_attributions').select('*').eq('tenant_id',tenantId),supabase.from('experiments').select('*').eq('tenant_id',tenantId),supabase.from('experiment_variants').select('*').eq('tenant_id',tenantId),supabase.from('integration_field_mappings').select('*').eq('tenant_id',tenantId)]);return {accounts:mapped<MediaAccount>(results[0]),campaigns:mapped<MediaCampaign>(results[1]),adGroups:mapped<MediaAdGroup>(results[2]),ads:mapped<MediaAd>(results[3]),creatives:mapped<MediaCreative>(results[4]),metrics:mapped<MediaDailyMetric>(results[5]),syncRuns:mapped<MediaSyncRun>(results[6]),landingPages:mapped<LandingPage>(results[7]),attributions:mapped<LeadAttribution>(results[8]),experiments:mapped<Experiment>(results[9]),experimentVariants:mapped<ExperimentVariant>(results[10]),mappings:mapped<IntegrationFieldMapping>(results[11])}}
  ,async finalizeImport(tenantId:string,integrationId:string,preview:MediaImportPreview){const records=preview.rows.filter((row)=>row.result.record&&!row.result.issues.some((issue)=>issue.severity==='error')).map((row)=>({...row.result.record,idempotencyKey:row.idempotencyKey}));if(demoMode)return {status:'completed',recordsProcessed:records.length};if(!supabase)throw new Error('Supabase is not configured.');const {data,error}=await supabase.rpc('axis_finalize_media_import',{p_tenant_id:tenantId,p_integration_id:integrationId,p_records:records});if(error)throw error;return data}
}
