import { release8Demo, release8DemoContexts } from '../data/release8Demo'
import { demoMode, supabase } from '../lib/supabase'
import type { AutomationAction, AutomationApproval, AutomationCircuitBreaker, AutomationExecution, AutomationLimits, AutomationNotification, AutomationPolicy, AutomationRollback, AutomationSettings, AutomationWorkspace } from '../automation/types'
import { createExecutionService, SandboxConnectorAdapter } from './executionService'

type DbRow = Record<string, unknown>
const demoState: AutomationWorkspace = structuredClone(release8Demo)
const demoExecutor = createExecutionService(new SandboxConnectorAdapter())
const object = (value: unknown) => value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : {}
const array = (value: unknown) => Array.isArray(value) ? value : []
const string = (value: unknown) => value == null ? '' : String(value)
const nullableString = (value: unknown) => value == null ? null : String(value)
const limits = (value: unknown): AutomationLimits => {
  const row = object(value)
  const numberOrNull = (key: string) => row[key] == null ? null : Number(row[key])
  return { maxPercentageIncrease: numberOrNull('maxPercentageIncrease'), maxPercentageDecrease: numberOrNull('maxPercentageDecrease'), maxAbsoluteDailyChange: numberOrNull('maxAbsoluteDailyChange'), maxDailyBudget: numberOrNull('maxDailyBudget'), maxMonthlySpend: numberOrNull('maxMonthlySpend'), maxActionsPerPeriod: Number(row.maxActionsPerPeriod ?? 1), periodMinutes: Number(row.periodMinutes ?? 60), cooldownMinutes: Number(row.cooldownMinutes ?? 0), maxAllocationPercentage: numberOrNull('maxAllocationPercentage'), maxRecoveryAttempts: numberOrNull('maxRecoveryAttempts') }
}
const rows = (result: { data: unknown[] | null; error: { message: string } | null }) => { if (result.error) throw new Error(result.error.message); return (result.data ?? []) as DbRow[] }

function mapSettings(row: DbRow | undefined, tenantId: string): AutomationSettings {
  if (!row) return { ...release8Demo.settings, tenantId }
  return { id: string(row.id), tenantId: string(row.tenant_id), defaultMode: string(row.default_mode) as AutomationSettings['defaultMode'], killSwitchEnabled: Boolean(row.kill_switch_enabled), freshnessBehavior: string(row.freshness_behavior) as AutomationSettings['freshnessBehavior'], minimumAutoConfidence: string(row.minimum_auto_confidence) as AutomationSettings['minimumAutoConfidence'], minimumSampleSize: Number(row.minimum_sample_size), executionMode: string(row.execution_mode) as AutomationSettings['executionMode'], updatedAt: string(row.updated_at) }
}
const mapPolicy = (row: DbRow): AutomationPolicy => ({ id: string(row.id), tenantId: string(row.tenant_id), name: string(row.name), engine: string(row.engine) as AutomationPolicy['engine'], actionType: string(row.action_type) as AutomationPolicy['actionType'], mode: string(row.mode) as AutomationPolicy['mode'], status: string(row.status) as AutomationPolicy['status'], priority: Number(row.priority), approvalRequired: Boolean(row.approval_required), requiredApprovals: Number(row.required_approvals), conditions: object(row.conditions), limits: limits(row.limits), updatedAt: string(row.updated_at) })
const mapAction = (row: DbRow): AutomationAction => ({ id: string(row.id), tenantId: string(row.tenant_id), policyId: string(row.policy_id), recommendationId: nullableString(row.recommendation_id), engine: string(row.engine) as AutomationAction['engine'], actionType: string(row.action_type) as AutomationAction['actionType'], targetType: string(row.target_type), targetId: string(row.target_id), targetLabel: string(row.target_label), status: string(row.status) as AutomationAction['status'], priority: string(row.priority) as AutomationAction['priority'], requestedBy: nullableString(row.requested_by), approvedBy: nullableString(row.approved_by), executedBy: nullableString(row.executed_by), parameters: object(row.parameters), previousState: object(row.previous_state), proposedState: object(row.proposed_state), evidence: array(row.evidence).map(String), expectedImpact: object(row.expected_impact) as Record<string, number | null>, actualImpact: row.actual_impact == null ? null : object(row.actual_impact) as Record<string, number | null>, impactBasis: nullableString(row.impact_basis) as AutomationAction['impactBasis'], confidence: string(row.confidence) as AutomationAction['confidence'], sampleSize: Number(row.sample_size), freshness: string(row.freshness) as AutomationAction['freshness'], risk: string(row.risk) as AutomationAction['risk'], idempotencyKey: string(row.idempotency_key), requiredApprovals: Number(row.required_approvals), approvalCount: Number(row.approval_count), rollbackStatus: string(row.rollback_status) as AutomationAction['rollbackStatus'], failureCode: nullableString(row.failure_code), failureMessage: nullableString(row.failure_message), createdAt: string(row.created_at), approvedAt: nullableString(row.approved_at), executedAt: nullableString(row.executed_at), completedAt: nullableString(row.completed_at), expiresAt: nullableString(row.expires_at) })
const mapApproval = (row: DbRow): AutomationApproval => ({ id: string(row.id), tenantId: string(row.tenant_id), actionId: string(row.action_id), decision: string(row.decision) as AutomationApproval['decision'], decidedBy: nullableString(row.decided_by), safeNote: string(row.safe_note), decidedAt: string(row.decided_at) })
const mapExecution = (row: DbRow): AutomationExecution => ({ id: string(row.id), tenantId: string(row.tenant_id), actionId: string(row.action_id), mode: string(row.execution_mode) as AutomationExecution['mode'], status: string(row.status) as AutomationExecution['status'], idempotencyKey: string(row.idempotency_key), previousState: object(row.previous_state), requestedState: object(row.requested_state), connectorStatus: string(row.connector_status), safeErrorCode: nullableString(row.safe_error_code), rollbackAvailable: Boolean(row.rollback_available), startedAt: string(row.started_at), completedAt: nullableString(row.completed_at) })
const mapRollback = (row: DbRow): AutomationRollback => ({ id: string(row.id), tenantId: string(row.tenant_id), actionId: string(row.action_id), executionId: string(row.execution_id), status: string(row.status) as AutomationRollback['status'], restoreState: object(row.restore_state), safeReason: string(row.safe_reason), requestedAt: string(row.requested_at), completedAt: nullableString(row.completed_at) })
const mapBreaker = (row: DbRow): AutomationCircuitBreaker => ({ id: string(row.id), tenantId: string(row.tenant_id), engine: string(row.engine) as AutomationCircuitBreaker['engine'], actionType: nullableString(row.action_type) as AutomationCircuitBreaker['actionType'], status: string(row.status) as AutomationCircuitBreaker['status'], reasonCode: string(row.reason_code), safeReason: string(row.safe_reason), evidence: object(row.evidence), triggeredAt: string(row.triggered_at), resolvedAt: nullableString(row.resolved_at) })
const mapNotification = (row: DbRow): AutomationNotification => ({ id: string(row.id), tenantId: string(row.tenant_id), type: string(row.type) as AutomationNotification['type'], severity: string(row.severity) as AutomationNotification['severity'], title: string(row.title), safeMessage: string(row.safe_message), actionId: nullableString(row.action_id), readAt: nullableString(row.read_at), createdAt: string(row.created_at) })

export const orchestrationService = {
  async getWorkspace(tenantId: string): Promise<AutomationWorkspace> {
    if (demoMode) return structuredClone({ ...demoState, policies: demoState.policies.filter((row) => row.tenantId === tenantId), actions: demoState.actions.filter((row) => row.tenantId === tenantId) })
    if (!supabase) throw new Error('Supabase is not configured.')
    const [settings, policies, actions, approvals, executions, rollbacks, breakers, notifications, controls] = await Promise.all([
      supabase.from('automation_settings').select('*').eq('tenant_id', tenantId).maybeSingle(), supabase.from('automation_policies').select('*').eq('tenant_id', tenantId).order('priority'), supabase.from('automation_actions').select('*').eq('tenant_id', tenantId).order('created_at', { ascending: false }).limit(250), supabase.from('automation_approvals').select('*').eq('tenant_id', tenantId).order('decided_at', { ascending: false }).limit(250), supabase.from('automation_executions').select('*').eq('tenant_id', tenantId).order('started_at', { ascending: false }).limit(250), supabase.from('automation_rollbacks').select('*').eq('tenant_id', tenantId).order('requested_at', { ascending: false }).limit(100), supabase.from('automation_circuit_breakers').select('*').eq('tenant_id', tenantId).order('triggered_at', { ascending: false }).limit(100), supabase.from('automation_notifications').select('*').eq('tenant_id', tenantId).order('created_at', { ascending: false }).limit(100), supabase.from('platform_automation_controls').select('suspended'),
    ])
    if (settings.error) throw new Error(settings.error.message)
    return { settings: mapSettings(settings.data as DbRow | undefined, tenantId), policies: rows(policies).map(mapPolicy), actions: rows(actions).map(mapAction), approvals: rows(approvals).map(mapApproval), executions: rows(executions).map(mapExecution), rollbacks: rows(rollbacks).map(mapRollback), circuitBreakers: rows(breakers).map(mapBreaker), notifications: rows(notifications).map(mapNotification), platformExecutionSuspended: rows(controls).some((row) => Boolean(row.suspended)) }
  },
  async decide(tenantId: string, actionId: string, decision: 'approved' | 'rejected', safeNote = '') {
    if (demoMode) { const action = demoState.actions.find((row) => row.id === actionId && row.tenantId === tenantId); if (!action) throw new Error('Automation action not found.'); if (!['draft', 'awaiting_approval', 'approved'].includes(action.status)) throw new Error('Action is not awaiting a decision.'); demoState.approvals.push({ id: crypto.randomUUID(), tenantId, actionId, decision, decidedBy: null, safeNote, decidedAt: new Date().toISOString() }); if (decision === 'rejected') { action.status = 'cancelled'; action.completedAt = new Date().toISOString() } else { action.approvalCount = Math.min(action.requiredApprovals, action.approvalCount + 1); action.status = action.approvalCount >= action.requiredApprovals ? 'approved' : 'awaiting_approval'; action.approvedAt = action.status === 'approved' ? new Date().toISOString() : null } return }
    if (!supabase) throw new Error('Supabase is not configured.'); const { error } = await supabase.rpc('axis_decide_automation_action', { p_tenant_id: tenantId, p_action_id: actionId, p_decision: decision, p_safe_note: safeNote }); if (error) throw error
  },
  async execute(tenantId: string, actionId: string) {
    if (demoMode) { const action = demoState.actions.find((row) => row.id === actionId && row.tenantId === tenantId); const policy = demoState.policies.find((row) => row.id === action?.policyId); if (!action || !policy) throw new Error('Automation action not found.'); const context = { ...release8DemoContexts[action.id], now: new Date().toISOString(), approvedCount: action.approvalCount }; const result = await demoExecutor.execute(demoState.settings, policy, action, context); if (!result.execution) { action.status = result.gate.status; action.failureCode = result.gate.status === 'blocked' ? 'EXECUTION_GATE' : null; action.failureMessage = result.gate.reasons.join(' '); return result } demoState.executions.unshift(result.execution); action.status = result.execution.status; action.executedAt = result.execution.startedAt; action.completedAt = result.execution.completedAt; action.failureCode = result.execution.safeErrorCode; return result }
    if (!supabase) throw new Error('Supabase is not configured.'); const { data, error } = await supabase.rpc('axis_simulate_automation_action', { p_tenant_id: tenantId, p_action_id: actionId }); if (error) throw error; return data
  },
  async rollback(tenantId: string, actionId: string, safeReason: string) {
    if (demoMode) { const action = demoState.actions.find((row) => row.id === actionId && row.tenantId === tenantId); const execution = demoState.executions.find((row) => row.actionId === actionId); if (!action || !execution) throw new Error('Execution not found.'); const result = await demoExecutor.rollback(action, execution, safeReason); if (result.status === 'not_available') throw new Error('Rollback is not available.'); action.status = result.status === 'succeeded' ? 'rolled_back' : 'failed'; action.rollbackStatus = result.status; demoState.rollbacks.unshift({ id: crypto.randomUUID(), tenantId, actionId, executionId: execution.id, status: result.status, restoreState: action.previousState, safeReason, requestedAt: new Date().toISOString(), completedAt: new Date().toISOString() }); return }
    if (!supabase) throw new Error('Supabase is not configured.'); const { error } = await supabase.rpc('axis_request_automation_rollback', { p_tenant_id: tenantId, p_action_id: actionId, p_safe_reason: safeReason }); if (error) throw error
  },
  async setKillSwitch(tenantId: string, enabled: boolean, safeReason: string) {
    if (demoMode) { demoState.settings.killSwitchEnabled = enabled; demoState.settings.updatedAt = new Date().toISOString(); return }
    if (!supabase) throw new Error('Supabase is not configured.'); const { error } = await supabase.rpc('axis_set_automation_kill_switch', { p_tenant_id: tenantId, p_enabled: enabled, p_safe_reason: safeReason }); if (error) throw error
  },
  async setPolicyMode(tenantId: string, policyId: string, mode: AutomationPolicy['mode']) {
    if (demoMode) { const policy = demoState.policies.find((row) => row.id === policyId && row.tenantId === tenantId); if (!policy) throw new Error('Policy not found.'); policy.mode = mode; policy.updatedAt = new Date().toISOString(); return }
    if (!supabase) throw new Error('Supabase is not configured.'); const { error } = await supabase.from('automation_policies').update({ mode }).eq('tenant_id', tenantId).eq('id', policyId); if (error) throw error
  },
}
