import { release5Demo } from '../data/release5Demo'
import { calculateRecoveryIntelligence } from '../recovery/domain'
import { demoMode,supabase } from '../lib/supabase'
import type { LeadOutcome, LeadRecovery, LeadRejection, RecoveryAttempt, RecoveryEvent, RecoveryPath, RecoveryPolicy, RecoveryReview } from '../types'

export interface RecoveryWorkspace { policies:RecoveryPolicy[];paths:RecoveryPath[];recoveries:LeadRecovery[];attempts:RecoveryAttempt[];reviews:RecoveryReview[];events:RecoveryEvent[] }
const demoState:RecoveryWorkspace=structuredClone({ policies:release5Demo.policies,paths:release5Demo.paths,recoveries:release5Demo.recoveries,attempts:release5Demo.attempts,reviews:release5Demo.reviews,events:release5Demo.events })
const scope=<T extends {tenantId:string}>(rows:T[],tenantId:string) => structuredClone(rows.filter((row) => row.tenantId===tenantId))
const must=<T>(result:{data:T;error:{message:string}|null}) => { if(result.error) throw new Error(result.error.message);return result.data }

export const recoveryService={
  async getWorkspace(tenantId:string):Promise<RecoveryWorkspace>{
    if(demoMode)return { policies:scope(demoState.policies,tenantId),paths:scope(demoState.paths,tenantId),recoveries:scope(demoState.recoveries,tenantId),attempts:scope(demoState.attempts,tenantId),reviews:scope(demoState.reviews,tenantId),events:scope(demoState.events,tenantId) }
    if(!supabase)throw new Error('Supabase is not configured.')
    const [policies,paths,recoveries,attempts,reviews,events]=await Promise.all([
      supabase.from('recovery_policies').select('id,tenant_id,name,status,priority,rejection_category,program_id,offer_id,source_buyer_id,max_attempts,max_attempts_per_buyer,max_destinations,max_lead_age_minutes,require_consent_confirmation,allow_secondary_host_post,allow_link_out,execution_mode,updated_at').eq('tenant_id',tenantId).order('priority'),
      supabase.from('recovery_paths').select('id,tenant_id,recovery_policy_id,buyer_id,offer_id,program_id,path_type,priority,status,payout_override,destination_reference,updated_at').eq('tenant_id',tenantId).order('priority'),
      supabase.from('lead_recoveries').select('id,tenant_id,lead_id,originating_rejection_id,recovery_policy_id,status,execution_mode,consent_status,consent_scope,consent_version,secondary_delivery_allowed,consent_confirmed_at,eligibility_code,explanation,recommended_path_id,idempotency_key,started_at,completed_at,recovery_value,incremental_cost,currency,created_at,updated_at').eq('tenant_id',tenantId).order('created_at',{ascending:false}).limit(250),
      supabase.from('recovery_attempts').select('id,tenant_id,lead_recovery_id,lead_id,buyer_id,offer_id,program_id,recovery_path_id,path_type,attempt_number,status,delivery_attempt_id,transaction_key,started_at,completed_at,reason,explanation,estimated_value,actual_value,incremental_cost,created_at').eq('tenant_id',tenantId).order('created_at',{ascending:false}).limit(500),
      supabase.from('recovery_reviews').select('id,tenant_id,lead_recovery_id,lead_id,reason_code,safe_reason,status,selected_path_id,resolved_by,resolved_at,created_at').eq('tenant_id',tenantId).order('created_at',{ascending:false}).limit(250),
      supabase.from('recovery_events').select('id,tenant_id,lead_recovery_id,lead_id,event_type,safe_detail,occurred_at').eq('tenant_id',tenantId).order('occurred_at'),
    ])
    return {
      policies:(must(policies)??[]).map((r) => ({id:r.id,tenantId:r.tenant_id,name:r.name,status:r.status as RecoveryPolicy['status'],priority:r.priority,rejectionCategory:r.rejection_category,programId:r.program_id,offerId:r.offer_id,sourceBuyerId:r.source_buyer_id,maxAttempts:r.max_attempts,maxAttemptsPerBuyer:r.max_attempts_per_buyer,maxDestinations:r.max_destinations,maxLeadAgeMinutes:r.max_lead_age_minutes,requireConsentConfirmation:r.require_consent_confirmation,allowSecondaryHostPost:r.allow_secondary_host_post,allowLinkOut:r.allow_link_out,executionMode:r.execution_mode as RecoveryPolicy['executionMode'],updatedAt:r.updated_at})),
      paths:(must(paths)??[]).map((r) => ({id:r.id,tenantId:r.tenant_id,recoveryPolicyId:r.recovery_policy_id,buyerId:r.buyer_id,offerId:r.offer_id,programId:r.program_id,pathType:r.path_type as RecoveryPath['pathType'],priority:r.priority,status:r.status as RecoveryPath['status'],payoutOverride:r.payout_override==null?null:Number(r.payout_override),destinationReference:r.destination_reference,updatedAt:r.updated_at})),
      recoveries:(must(recoveries)??[]).map((r) => ({id:r.id,tenantId:r.tenant_id,leadId:r.lead_id,originatingRejectionId:r.originating_rejection_id,recoveryPolicyId:r.recovery_policy_id,status:r.status as LeadRecovery['status'],executionMode:r.execution_mode as LeadRecovery['executionMode'],consentStatus:r.consent_status as LeadRecovery['consentStatus'],consentScope:r.consent_scope,consentVersion:r.consent_version,secondaryDeliveryAllowed:r.secondary_delivery_allowed,consentConfirmedAt:r.consent_confirmed_at,eligibilityCode:r.eligibility_code,explanation:Array.isArray(r.explanation)?r.explanation:[],recommendedPathId:r.recommended_path_id,idempotencyKey:r.idempotency_key,startedAt:r.started_at,completedAt:r.completed_at,recoveryValue:r.recovery_value==null?null:Number(r.recovery_value),incrementalCost:r.incremental_cost==null?null:Number(r.incremental_cost),currency:r.currency,createdAt:r.created_at,updatedAt:r.updated_at})),
      attempts:(must(attempts)??[]).map((r) => ({id:r.id,tenantId:r.tenant_id,leadRecoveryId:r.lead_recovery_id,leadId:r.lead_id,buyerId:r.buyer_id,offerId:r.offer_id,programId:r.program_id,recoveryPathId:r.recovery_path_id,pathType:r.path_type as RecoveryAttempt['pathType'],attemptNumber:r.attempt_number,status:r.status as RecoveryAttempt['status'],deliveryAttemptId:r.delivery_attempt_id,transactionKey:r.transaction_key,startedAt:r.started_at,completedAt:r.completed_at,reason:r.reason??'',explanation:Array.isArray(r.explanation)?r.explanation:[],estimatedValue:r.estimated_value==null?null:Number(r.estimated_value),actualValue:r.actual_value==null?null:Number(r.actual_value),incrementalCost:r.incremental_cost==null?null:Number(r.incremental_cost),createdAt:r.created_at})),
      reviews:(must(reviews)??[]).map((r) => ({id:r.id,tenantId:r.tenant_id,leadRecoveryId:r.lead_recovery_id,leadId:r.lead_id,reasonCode:r.reason_code,safeReason:r.safe_reason,status:r.status as RecoveryReview['status'],selectedPathId:r.selected_path_id,resolvedBy:r.resolved_by,resolvedAt:r.resolved_at,createdAt:r.created_at})),
      events:(must(events)??[]).map((r) => ({id:r.id,tenantId:r.tenant_id,leadRecoveryId:r.lead_recovery_id,leadId:r.lead_id,eventType:r.event_type,safeDetail:r.safe_detail,occurredAt:r.occurred_at})),
    }
  },
  report(tenantId:string,rejections:LeadRejection[],workspace:RecoveryWorkspace,outcomes:LeadOutcome[]){return calculateRecoveryIntelligence(tenantId,rejections,workspace.recoveries,workspace.attempts,outcomes)},
  async savePolicy(input:Omit<RecoveryPolicy,'updatedAt'>){
    if(demoMode){const existing=demoState.policies.find((row) => row.id===input.id&&row.tenantId===input.tenantId);if(existing)Object.assign(existing,input,{updatedAt:new Date().toISOString()});else demoState.policies.push({...input,updatedAt:new Date().toISOString()});return}
    if(!supabase)throw new Error('Supabase is not configured.');const payload={tenant_id:input.tenantId,name:input.name,status:input.status,priority:input.priority,rejection_category:input.rejectionCategory,program_id:input.programId,offer_id:input.offerId,source_buyer_id:input.sourceBuyerId,max_attempts:input.maxAttempts,max_attempts_per_buyer:input.maxAttemptsPerBuyer,max_destinations:input.maxDestinations,max_lead_age_minutes:input.maxLeadAgeMinutes,require_consent_confirmation:input.requireConsentConfirmation,allow_secondary_host_post:input.allowSecondaryHostPost,allow_link_out:input.allowLinkOut,execution_mode:input.executionMode};const {error}=await supabase.from('recovery_policies').upsert({...payload,id:input.id},{onConflict:'id'});if(error)throw error
  },
  async savePath(input:Omit<RecoveryPath,'updatedAt'>){
    if(demoMode){const existing=demoState.paths.find((row) => row.id===input.id&&row.tenantId===input.tenantId);if(existing)Object.assign(existing,input,{updatedAt:new Date().toISOString()});else demoState.paths.push({...input,updatedAt:new Date().toISOString()});return}
    if(!supabase)throw new Error('Supabase is not configured.');const payload={id:input.id,tenant_id:input.tenantId,recovery_policy_id:input.recoveryPolicyId,buyer_id:input.buyerId,offer_id:input.offerId,program_id:input.programId,path_type:input.pathType,priority:input.priority,status:input.status,payout_override:input.payoutOverride,destination_reference:input.destinationReference};const {error}=await supabase.from('recovery_paths').upsert(payload,{onConflict:'id'});if(error)throw error
  },
  async decide(tenantId:string,recoveryId:string,decision:'approve'|'block'|'resolve',pathId:string|null,reason:string){
    if(demoMode){const row=demoState.recoveries.find((item) => item.id===recoveryId&&item.tenantId===tenantId);if(!row)throw new Error('Recovery not found.');row.status=decision==='approve'?'queued':decision==='block'?'blocked':row.status;row.recommendedPathId=pathId??row.recommendedPathId;row.updatedAt=new Date().toISOString();const review=demoState.reviews.find((item) => item.leadRecoveryId===recoveryId);if(review){review.status=decision==='approve'?'approved':decision==='block'?'blocked':'resolved';review.selectedPathId=pathId;review.resolvedAt=new Date().toISOString()}demoState.events.push({id:crypto.randomUUID(),tenantId,leadRecoveryId:recoveryId,leadId:row.leadId,eventType:`recovery_${decision}d`,safeDetail:reason||'Authorized recovery decision recorded.',occurredAt:new Date().toISOString()});return}
    if(!supabase)throw new Error('Supabase is not configured.');const {error}=await supabase.rpc('axis_decide_recovery',{p_tenant_id:tenantId,p_recovery_id:recoveryId,p_decision:decision,p_path_id:pathId,p_safe_reason:reason});if(error)throw error
  },
}
