import type { IntegrationFieldMapping,MediaPlatform } from '../../types'
import type { CanonicalMediaMetricRecord,ExternalMediaRow,MediaImportIssue,MediaNormalizationResult } from './types'

const aliases:Record<string,string[]>={external_account_id:['account id','account_id'],external_campaign_id:['campaign id','campaign_id'],campaign_name:['campaign name','campaign'],external_ad_group_id:['ad set id','ad group id','ad_group_id'],ad_group_name:['ad set name','ad group name','ad_group'],external_ad_id:['ad id','ad_id'],ad_name:['ad name','ad'],external_creative_id:['creative id','creative_id'],creative_name:['creative name','creative'],metric_date:['date','day'],currency:['currency','currency code'],impressions:['impressions'],clicks:['clicks','link clicks'],spend:['amount spent','cost','spend'],platform_conversions:['results','conversions'],reach:['reach'],frequency:['frequency']}
const value=(row:ExternalMediaRow,mappings:IntegrationFieldMapping[],axisField:string)=>{const mapping=mappings.find((item)=>item.axisField===axisField);if(mapping)return (row[mapping.externalField]??'').trim();const key=Object.keys(row).find((candidate)=>aliases[axisField]?.includes(candidate.trim().toLowerCase()));return key?(row[key]??'').trim():''}
const numeric=(raw:string,field:string,issues:MediaImportIssue[],nullable=false)=>{if(!raw&&nullable)return null;const parsed=Number(raw.replaceAll(',','').replace('$',''));if(!Number.isFinite(parsed)||parsed<0){issues.push({code:`INVALID_${field.toUpperCase()}`,message:`${field} must be a non-negative number.`,severity:'error'});return nullable?null:0}return parsed}
export function normalizeMediaRows(platform:MediaPlatform,rows:ExternalMediaRow[],mappings:IntegrationFieldMapping[]):MediaNormalizationResult[]{return rows.map((row,index)=>{const issues:MediaImportIssue[]=[];const externalAccountId=value(row,mappings,'external_account_id');const externalCampaignId=value(row,mappings,'external_campaign_id');const campaignName=value(row,mappings,'campaign_name');const metricDate=value(row,mappings,'metric_date');if(!externalAccountId)issues.push({code:'MISSING_ACCOUNT_ID',message:'External account identifier is required.',severity:'error'});if(!externalCampaignId)issues.push({code:'MISSING_CAMPAIGN_ID',message:'External campaign identifier is required.',severity:'error'});if(!campaignName)issues.push({code:'MISSING_CAMPAIGN_NAME',message:'Campaign name is required.',severity:'error'});if(!metricDate||Number.isNaN(Date.parse(`${metricDate}T00:00:00Z`)))issues.push({code:'INVALID_DATE',message:'A valid metric date is required.',severity:'error'});const record:CanonicalMediaMetricRecord={rowNumber:index+2,platform,externalAccountId,externalCampaignId,campaignName,externalAdGroupId:value(row,mappings,'external_ad_group_id'),adGroupName:value(row,mappings,'ad_group_name'),externalAdId:value(row,mappings,'external_ad_id'),adName:value(row,mappings,'ad_name'),externalCreativeId:value(row,mappings,'external_creative_id'),creativeName:value(row,mappings,'creative_name'),metricDate,currency:value(row,mappings,'currency')||'USD',impressions:numeric(value(row,mappings,'impressions'),'impressions',issues)??0,clicks:numeric(value(row,mappings,'clicks'),'clicks',issues)??0,spend:numeric(value(row,mappings,'spend'),'spend',issues,true),platformConversions:numeric(value(row,mappings,'platform_conversions'),'platform conversions',issues)??0,reach:numeric(value(row,mappings,'reach'),'reach',issues,true),frequency:numeric(value(row,mappings,'frequency'),'frequency',issues,true)};return {record:issues.some((item)=>item.severity==='error')?null:record,issues}})}
export const mediaMetricIdempotencyKey=(record:CanonicalMediaMetricRecord)=>[record.platform,record.externalAccountId,record.externalCampaignId,record.externalAdGroupId||'-',record.externalAdId||'-',record.metricDate].join(':')
export const campaignSyncKey=(tenantId:string,platform:MediaPlatform,accountId:string,externalCampaignId:string)=>`${tenantId}:${platform}:${accountId}:${externalCampaignId}`
