import { useCallback, useEffect, useState, type ReactNode } from 'react'
import { AlertOctagon, ArrowLeft, ArrowRight, Ban, BellRing, CheckCircle2, CircleDollarSign, Gauge, GitBranch, PauseCircle, Play, RotateCcw, Settings2, ShieldCheck, SlidersHorizontal, Sparkles, Target, Workflow, XCircle } from 'lucide-react'
import { Link, NavLink, Navigate, useParams } from 'react-router-dom'
import { EmptyState, PageHeader, Status } from './components/Shell'
import { useApp } from './context/AppContext'
import { automationValue } from './automation/domain'
import type { AutomationAction, AutomationEngine, AutomationWorkspace } from './automation/types'
import { orchestrationService } from './services/orchestrationService'

const number = new Intl.NumberFormat('en-US', { maximumFractionDigits: 1 })
const money = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 })
const date = (value: string | null) => value ? new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', year: 'numeric', hour: 'numeric', minute: '2-digit' }).format(new Date(value)) : 'Unavailable'
const label = (value: string) => value.replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase())

function useAutomation() {
  const { tenant } = useApp()
  const [workspace, setWorkspace] = useState<AutomationWorkspace | null>(null)
  const [error, setError] = useState('')
  const load = useCallback(async () => { try { setWorkspace(await orchestrationService.getWorkspace(tenant.id)); setError('') } catch { setError('Automation controls could not be loaded safely.') } }, [tenant.id])
  useEffect(() => { void load() }, [load])
  return { workspace, error, reload: load, tenantId: tenant.id }
}

function Loading({ error }: { error: string }) { return <section className="panel intelligence-loading"><div className="loader"/><p>{error || 'Loading automation controls…'}</p></section> }
function AutomationNav() { const items = [['/automation', 'Overview'], ['/automation/approvals', 'Approvals'], ['/automation/policies', 'Policies'], ['/automation/actions', 'Actions'], ['/automation/executions', 'Execution History'], ['/automation/safeguards', 'Safeguards'], ['/automation/notifications', 'Notifications'], ['/automation/settings', 'Settings']]; return <nav className="automation-tabs" aria-label="Automation Center">{items.map(([to, text]) => <NavLink key={to} to={to} end={to === '/automation'}>{text}</NavLink>)}</nav> }
function AutomationHeader({ title, description, action }: { title: string; description: string; action?: ReactNode }) { return <><PageHeader eyebrow="Axis Automation" title={title} description={description} action={action}/><AutomationNav/></> }
function Kpi({ label: title, value, detail }: { label: string; value: string; detail: string }) { return <article className="automation-kpi"><span>{title}</span><strong>{value}</strong><small>{detail}</small></article> }
function ModeBadge({ mode }: { mode: string }) { return <span className={`mode-badge mode-${mode}`}>{label(mode)}</span> }
function ExecutionBadge({ mode }: { mode: string }) { return <span className={`execution-badge execution-${mode}`}>{mode.toUpperCase()}</span> }

export function AutomationOverviewPage() {
  const { workspace, error } = useAutomation()
  if (!workspace) return <Loading error={error}/>
  const awaiting = workspace.actions.filter((row) => row.status === 'awaiting_approval').length
  const executing = workspace.actions.filter((row) => ['scheduled', 'executing'].includes(row.status)).length
  const completed = workspace.actions.filter((row) => ['succeeded', 'rolled_back'].includes(row.status)).length
  const failed = workspace.actions.filter((row) => ['failed', 'blocked'].includes(row.status)).length
  const values = automationValue(workspace.actions)
  return <><AutomationHeader title="Automation Control Center" description="Bounded, approval-aware orchestration across the Axis operating engines." action={<Link className="primary-button" to="/automation/approvals"><ShieldCheck size={15}/> Review approvals</Link>}/>
    <section className={`automation-state-banner ${workspace.settings.killSwitchEnabled || workspace.platformExecutionSuspended ? 'is-paused' : ''}`}><div><Workflow/><span>Automation mode</span><strong>{label(workspace.settings.defaultMode)}</strong></div><div><ExecutionBadge mode={workspace.settings.executionMode}/><span>{workspace.settings.killSwitchEnabled ? 'Tenant kill switch enabled' : workspace.platformExecutionSuspended ? 'Platform execution suspended' : 'Safeguards active'}</span></div></section>
    <section className="automation-kpis"><Kpi label="Awaiting Approval" value={String(awaiting)} detail="Authorized decision required"/><Kpi label="Executing" value={String(executing)} detail="Scheduled or in progress"/><Kpi label="Completed" value={String(completed)} detail="Successful or rolled back"/><Kpi label="Failed / Blocked" value={String(failed)} detail="Preserved for review"/><Kpi label="Observed Value" value={values.revenueRecovered == null ? 'Unavailable' : money.format(values.revenueRecovered)} detail="Observed, not causal"/><Kpi label="Active Policies" value={String(workspace.policies.filter((row) => row.status === 'active').length)} detail="Tenant-scoped boundaries"/><Kpi label="Circuit Breakers" value={String(workspace.circuitBreakers.filter((row) => row.status !== 'resolved').length)} detail="Open or under review"/><Kpi label="Rollbacks" value={String(workspace.actions.filter((row) => row.status === 'rolled_back').length)} detail="Restored previous state"/></section>
    <div className="automation-grid"><section className="panel"><div className="panel-heading"><div><h2>Engine health</h2><p>Execution mode, queue, and safeguard state</p></div><Gauge/></div><div className="engine-health">{(['acquire', 'convert', 'route', 'recover', 'optimize'] as AutomationEngine[]).map((engine) => <EngineHealth key={engine} engine={engine} workspace={workspace}/>)}</div></section><section className="panel"><div className="panel-heading"><div><h2>Operator attention</h2><p>Highest-priority controlled actions</p></div><AlertOctagon/></div><div className="attention-list">{workspace.actions.filter((row) => ['awaiting_approval', 'failed', 'blocked'].includes(row.status)).slice(0, 5).map((row) => <Link to={`/automation/actions/${row.id}`} key={row.id}><Status value={row.status}/><div><strong>{row.targetLabel}</strong><span>{label(row.actionType)} · {label(row.engine)}</span></div><ArrowRight size={14}/></Link>)}</div></section></div>
    <section className="panel safety-strip"><ShieldCheck/><div><strong>Bounded autonomy is active</strong><span>Authorization, policy, freshness, confidence, budget, capacity, compliance, rate, cooldown, idempotency, and rollback gates are evaluated before execution.</span></div><Link className="secondary-button" to="/automation/safeguards">View safeguards</Link></section>
  </>
}

function EngineHealth({ engine, workspace }: { engine: AutomationEngine; workspace: AutomationWorkspace }) {
  const policies = workspace.policies.filter((row) => row.engine === engine && row.status === 'active')
  const breaker = workspace.circuitBreakers.find((row) => row.engine === engine && row.status !== 'resolved')
  const mode = policies[0]?.mode ?? 'disabled'
  return <article><span className="engine-icon-small">{engine === 'acquire' ? <Target/> : engine === 'route' ? <GitBranch/> : engine === 'recover' ? <RotateCcw/> : engine === 'optimize' ? <Gauge/> : <Sparkles/>}</span><div><strong>{label(engine)}</strong><small>{breaker ? 'Paused by circuit breaker' : policies.length ? 'Healthy' : 'No active policy'}</small></div><ModeBadge mode={mode}/></article>
}

export function ApprovalCenterPage() {
  const { workspace, error } = useAutomation(); const [engine, setEngine] = useState('all')
  if (!workspace) return <Loading error={error}/>
  const rows = workspace.actions.filter((row) => ['draft', 'awaiting_approval', 'approved'].includes(row.status) && (engine === 'all' || row.engine === engine))
  return <><AutomationHeader title="Approval Center" description="Inspect evidence, risk, policy, and rollback availability before authorizing execution."/><div className="automation-filters"><label>Engine<select value={engine} onChange={(event) => setEngine(event.target.value)}><option value="all">All engines</option>{['acquire', 'convert', 'route', 'recover', 'optimize', 'integration'].map((value) => <option key={value}>{value}</option>)}</select></label><span>High-risk actions are reviewed individually. Bulk approval is disabled.</span></div><ActionTable rows={rows} mode={workspace.settings.executionMode}/></>
}

export function AutomationPoliciesPage() {
  const { workspace, error, reload, tenantId } = useAutomation(); const { allowed } = useApp(); const [busy, setBusy] = useState('')
  if (!workspace) return <Loading error={error}/>
  async function change(policyId: string, mode: AutomationPolicyMode) { setBusy(policyId); try { await orchestrationService.setPolicyMode(tenantId, policyId, mode); await reload() } finally { setBusy('') } }
  return <><AutomationHeader title="Automation Policies" description="Configure tenant-scoped execution modes and limits without granting unrestricted autonomy."/><section className="policy-grid">{workspace.policies.map((policy) => <article className="panel policy-card" key={policy.id}><div className="policy-head"><span className="engine-icon-small"><SlidersHorizontal/></span><div><strong>{policy.name}</strong><small>{label(policy.engine)} · {label(policy.actionType)}</small></div><Status value={policy.status}/></div><dl><div><dt>Approval</dt><dd>{policy.requiredApprovals} required</dd></div><div><dt>Cooldown</dt><dd>{policy.limits.cooldownMinutes} min</dd></div><div><dt>Rate</dt><dd>{policy.limits.maxActionsPerPeriod} / {policy.limits.periodMinutes} min</dd></div><div><dt>Budget increase</dt><dd>{policy.limits.maxPercentageIncrease == null ? 'Not applicable' : `${policy.limits.maxPercentageIncrease}% max`}</dd></div></dl><label>Policy mode<select value={policy.mode} disabled={!allowed('automation:configure') || busy === policy.id} onChange={(event) => void change(policy.id, event.target.value as AutomationPolicyMode)}>{['advisory', 'approval_required', 'bounded_auto', 'disabled'].map((mode) => <option key={mode} value={mode}>{label(mode)}</option>)}</select></label></article>)}</section></>
}
type AutomationPolicyMode = 'advisory' | 'approval_required' | 'bounded_auto' | 'disabled'

export function AutomationActionsPage() {
  const { workspace, error } = useAutomation(); const [status, setStatus] = useState('all')
  if (!workspace) return <Loading error={error}/>
  const rows = workspace.actions.filter((row) => status === 'all' || row.status === status)
  return <><AutomationHeader title="Automation Actions" description="Every proposed, blocked, executed, failed, and rolled-back action remains inspectable."/><div className="automation-filters"><label>Status<select value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">All statuses</option>{['draft', 'awaiting_approval', 'approved', 'executing', 'succeeded', 'failed', 'blocked', 'rolled_back', 'cancelled'].map((value) => <option key={value}>{value}</option>)}</select></label></div><ActionTable rows={rows} mode={workspace.settings.executionMode}/></>
}

function ActionTable({ rows, mode }: { rows: AutomationAction[]; mode: string }) { return <section className="panel table-panel">{rows.length ? <div className="table-scroll"><table><thead><tr><th>Action</th><th>Engine</th><th>Target</th><th>Risk</th><th>Confidence</th><th>Mode</th><th>Status</th><th>Created</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><Link className="text-button" to={`/automation/actions/${row.id}`}>{label(row.actionType)} <ArrowRight size={13}/></Link></td><td>{label(row.engine)}</td><td><strong>{row.targetLabel}</strong></td><td><Status value={row.risk}/></td><td>{label(row.confidence)} · n={number.format(row.sampleSize)}</td><td><ExecutionBadge mode={mode}/></td><td><Status value={row.status}/></td><td>{date(row.createdAt)}</td></tr>)}</tbody></table></div> : <EmptyState title="No automation actions match" description="Adjust the filters or wait for an evidence-backed action."/>}</section> }

export function AutomationActionDetailPage() {
  const { actionId } = useParams(); const { workspace, error, reload, tenantId } = useAutomation(); const { allowed } = useApp(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [confirm, setConfirm] = useState<'approve' | 'reject' | 'execute' | 'rollback' | null>(null)
  if (!workspace) return <Loading error={error}/>
  const action = workspace.actions.find((row) => row.id === actionId); if (!action) return <Navigate to="/automation/actions" replace/>
  const policy = workspace.policies.find((row) => row.id === action.policyId)
  async function perform() { const currentAction = action; if (!confirm || !currentAction) return; setBusy(true); setMessage(''); try { if (confirm === 'approve') await orchestrationService.decide(tenantId, currentAction.id, 'approved', 'Evidence and policy reviewed.'); if (confirm === 'reject') await orchestrationService.decide(tenantId, currentAction.id, 'rejected', 'Action rejected after operator review.'); if (confirm === 'execute') await orchestrationService.execute(tenantId, currentAction.id); if (confirm === 'rollback') await orchestrationService.rollback(tenantId, currentAction.id, 'Operator requested restoration of the previous state.'); await reload(); setConfirm(null) } catch { setMessage('The action was not changed. Review its status and safety gates.') } finally { setBusy(false) } }
  const canDecide = allowed('automation:approve') && ['draft', 'awaiting_approval'].includes(action.status)
  return <><Link className="back-link" to="/automation/actions"><ArrowLeft size={15}/> Back to actions</Link><PageHeader eyebrow={`${label(action.engine)} automation`} title={label(action.actionType)} description={`Controlled action for ${action.targetLabel}.`} action={<div className="header-actions"><ExecutionBadge mode={workspace.settings.executionMode}/><Status value={action.status}/></div>}/>{message && <p className="form-error page-error" role="alert">{message}</p>}
    <section className="action-preview panel"><div className="preview-heading"><div><span>Execution preview</span><h2>{action.targetLabel}</h2><p>{action.evidence[0] ?? 'No evidence summary is available.'}</p></div><RiskPanel action={action}/></div><div className="state-comparison"><StateCard title="Current state" state={action.previousState}/><ArrowRight/><StateCard title="Proposed state" state={action.proposedState}/></div><div className="evidence-grid"><Detail label="Policy" value={policy?.name ?? 'Unavailable'}/><Detail label="Confidence" value={`${label(action.confidence)} · sample ${number.format(action.sampleSize)}`}/><Detail label="Data freshness" value={label(action.freshness)}/><Detail label="Approvals" value={`${action.approvalCount} of ${action.requiredApprovals}`}/><Detail label="Rollback" value={label(action.rollbackStatus)}/><Detail label="Recommendation" value={action.recommendationId ? 'Linked and preserved' : 'Not linked'}/></div></section>
    <div className="automation-grid"><section className="panel"><div className="panel-heading"><div><h2>Why Axis proposed this</h2><p>PII-free aggregate evidence</p></div><ShieldCheck/></div><ul className="evidence-list">{action.evidence.map((item) => <li key={item}><CheckCircle2/>{item}</li>)}</ul></section><section className="panel"><div className="panel-heading"><div><h2>Expected impact</h2><p>Estimate, not a guarantee</p></div><CircleDollarSign/></div><MetricList values={action.expectedImpact}/>{action.actualImpact && <><h3 className="impact-heading">Actual impact · {action.impactBasis}</h3><MetricList values={action.actualImpact}/></>}</section></div>
    {(canDecide || (allowed('automation:execute') && action.status === 'approved') || (allowed('automation:rollback') && action.status === 'succeeded' && action.rollbackStatus === 'available')) && <section className="panel action-controls"><div><strong>Operator controls</strong><span>Each decision is tenant-scoped and audited.</span></div>{canDecide && <><button className="secondary-button danger-outline" onClick={() => setConfirm('reject')}><XCircle size={15}/> Reject</button><button className="primary-button" onClick={() => setConfirm('approve')}><ShieldCheck size={15}/> Approve</button></>}{allowed('automation:execute') && action.status === 'approved' && <button className="primary-button" onClick={() => setConfirm('execute')}><Play size={15}/> Execute simulated action</button>}{allowed('automation:rollback') && action.status === 'succeeded' && action.rollbackStatus === 'available' && <button className="secondary-button danger-outline" onClick={() => setConfirm('rollback')}><RotateCcw size={15}/> Request rollback</button>}</section>}
    {confirm && <ConfirmDialog kind={confirm} busy={busy} onCancel={() => setConfirm(null)} onConfirm={() => void perform()}/>}</>
}

function RiskPanel({ action }: { action: AutomationAction }) { return <div className={`risk-panel risk-${action.risk}`}><AlertOctagon/><span>Risk</span><strong>{label(action.risk)}</strong></div> }
function StateCard({ title, state }: { title: string; state: Record<string, unknown> }) { const entries = Object.entries(state); return <article><span>{title}</span>{entries.length ? entries.map(([key, value]) => <div key={key}><small>{label(key)}</small><strong>{typeof value === 'number' && key.toLowerCase().includes('budget') ? money.format(value) : String(value)}</strong></div>) : <strong>Not available</strong>}</article> }
function Detail({ label: title, value }: { label: string; value: string }) { return <div><span>{title}</span><strong>{value}</strong></div> }
function MetricList({ values }: { values: Record<string, number | null> }) { const entries = Object.entries(values); return <dl className="metric-list">{entries.length ? entries.map(([key, value]) => <div key={key}><dt>{label(key)}</dt><dd>{value == null ? 'Unavailable' : key.toLowerCase().includes('revenue') || key.toLowerCase().includes('contribution') ? money.format(value) : number.format(value)}</dd></div>) : <div><dt>Impact</dt><dd>Unavailable</dd></div>}</dl> }
function ConfirmDialog({ kind, busy, onCancel, onConfirm }: { kind: string; busy: boolean; onCancel: () => void; onConfirm: () => void }) { const destructive = kind === 'reject' || kind === 'rollback'; return <div className="modal-backdrop"><div className="modal confirm-dialog" role="dialog" aria-modal="true" aria-labelledby="automation-confirm-title"><span className="eyebrow">Controlled operator action</span><h2 id="automation-confirm-title">Confirm {kind}</h2><p>{kind === 'execute' ? 'This staging action will be clearly recorded as SIMULATED. No external account will be changed.' : kind === 'rollback' ? 'Axis will attempt to restore the recorded previous state using the simulated adapter.' : `This ${kind} decision will be preserved in the immutable approval history.`}</p><div className="modal-actions"><button className="secondary-button" disabled={busy} onClick={onCancel}>Cancel</button><button className={destructive ? 'danger-button' : 'primary-button'} disabled={busy} onClick={onConfirm}>{busy ? 'Working…' : `Confirm ${kind}`}</button></div></div></div> }

export function ExecutionHistoryPage() {
  const { workspace, error } = useAutomation(); if (!workspace) return <Loading error={error}/>
  return <><AutomationHeader title="Execution History" description="Immutable, redacted execution outcomes with explicit simulated or live mode."/><section className="panel table-panel">{workspace.executions.length ? <div className="table-scroll"><table><thead><tr><th>Action</th><th>Mode</th><th>Result</th><th>Connector status</th><th>Rollback</th><th>Started</th><th>Completed</th></tr></thead><tbody>{workspace.executions.map((row) => { const action = workspace.actions.find((item) => item.id === row.actionId); return <tr key={row.id}><td><Link className="text-button" to={`/automation/actions/${row.actionId}`}>{action?.targetLabel ?? row.actionId}</Link></td><td><ExecutionBadge mode={row.mode}/></td><td><Status value={row.status}/></td><td>{row.connectorStatus}</td><td>{row.rollbackAvailable ? 'Available' : 'Not available'}</td><td>{date(row.startedAt)}</td><td>{date(row.completedAt)}</td></tr>})}</tbody></table></div> : <EmptyState title="No execution history" description="A new tenant begins without automation executions."/>}</section></>
}

export function AutomationSafeguardsPage() {
  const { workspace, error, reload, tenantId } = useAutomation(); const { allowed } = useApp(); const [confirm, setConfirm] = useState(false); const [busy, setBusy] = useState(false)
  if (!workspace) return <Loading error={error}/>
  async function toggle() { setBusy(true); try { await orchestrationService.setKillSwitch(tenantId, !workspace!.settings.killSwitchEnabled, 'Tenant administrator changed the automation safety state.'); await reload(); setConfirm(false) } finally { setBusy(false) } }
  return <><AutomationHeader title="Automation Safeguards" description="Kill switches and circuit breakers halt execution without deleting evidence or advisory recommendations."/><section className={`kill-switch panel ${workspace.settings.killSwitchEnabled ? 'enabled' : ''}`}><span><Ban/></span><div><strong>{workspace.settings.killSwitchEnabled ? 'All tenant automation is disabled' : 'Tenant automation is enabled'}</strong><p>New bounded-auto executions are blocked when disabled. Recommendations, approvals, queued records, and audit history remain intact.</p></div>{allowed('automation:emergency_stop') && <button className={workspace.settings.killSwitchEnabled ? 'primary-button' : 'danger-button'} onClick={() => setConfirm(true)}>{workspace.settings.killSwitchEnabled ? 'Enable automation' : 'Disable all automation'}</button>}</section><div className="automation-grid"><section className="panel"><div className="panel-heading"><div><h2>Circuit breakers</h2><p>Automatic containment for abnormal conditions</p></div><PauseCircle/></div><div className="breaker-list">{workspace.circuitBreakers.map((row) => <article key={row.id}><Status value={row.status}/><div><strong>{label(row.engine)} · {row.actionType ? label(row.actionType) : 'All actions'}</strong><span>{row.safeReason}</span><small>{row.reasonCode} · {date(row.triggeredAt)}</small></div></article>)}</div></section><section className="panel"><div className="panel-heading"><div><h2>Execution gates</h2><p>Every required gate fails closed</p></div><ShieldCheck/></div><div className="gate-grid">{['Tenant active', 'Connector active', 'Server credentials', 'Policy permitted', 'Authorized capability', 'Fresh data', 'Confidence threshold', 'Budget and capacity', 'Compliance clearance', 'Cooldown and rate', 'Idempotency', 'Rollback strategy'].map((item) => <span key={item}><CheckCircle2/>{item}</span>)}</div></section></div>{confirm && <ConfirmDialog kind={workspace.settings.killSwitchEnabled ? 'enable automation' : 'disable all automation'} busy={busy} onCancel={() => setConfirm(false)} onConfirm={() => void toggle()}/>}</>
}

export function AutomationNotificationsPage() { const { workspace, error } = useAutomation(); if (!workspace) return <Loading error={error}/>; return <><AutomationHeader title="Automation Notifications" description="PII-safe operational alerts for approvals, failures, safeguards, and thresholds."/><section className="panel notification-list">{workspace.notifications.length ? workspace.notifications.map((row) => <article key={row.id} className={`notification-${row.severity}`}><BellRing/><div><strong>{row.title}</strong><span>{row.safeMessage}</span><small>{date(row.createdAt)}</small></div>{row.actionId && <Link className="text-button" to={`/automation/actions/${row.actionId}`}>Inspect <ArrowRight size={13}/></Link>}</article>) : <EmptyState title="No automation notifications" description="Important orchestration events will appear here without lead PII."/>}</section></> }

export function AutomationSettingsPage() { const { workspace, error } = useAutomation(); if (!workspace) return <Loading error={error}/>; const settings = workspace.settings; return <><AutomationHeader title="Automation Settings" description="Tenant defaults remain conservative and live execution remains server-controlled."/><div className="settings-grid"><section className="panel"><div className="panel-heading"><div><h2>Tenant defaults</h2><p>New tenants begin in Advisory mode</p></div><Settings2/></div><dl className="detail-list"><div><dt>Default mode</dt><dd><ModeBadge mode={settings.defaultMode}/></dd></div><div><dt>Execution adapter</dt><dd><ExecutionBadge mode={settings.executionMode}/></dd></div><div><dt>Minimum confidence</dt><dd>{label(settings.minimumAutoConfidence)}</dd></div><div><dt>Minimum sample</dt><dd>{number.format(settings.minimumSampleSize)}</dd></div><div><dt>Stale-data behavior</dt><dd>{label(settings.freshnessBehavior)}</dd></div></dl></section><section className="panel"><div className="panel-heading"><div><h2>Security boundary</h2><p>Execution authority does not belong to AI or browser code</p></div><ShieldCheck/></div><div className="boundary-flow"><span>AI / Rules<br/><small>Recommend</small></span><ArrowRight/><span>Axis Policy<br/><small>Authorize</small></span><ArrowRight/><span>Approval<br/><small>Control</small></span><ArrowRight/><span>Trusted Server<br/><small>Execute</small></span></div><p className="boundary-note">Live connector credentials are unavailable to this application bundle. Staging uses a clearly labeled simulated adapter.</p></section></div></> }
