import type { ReactNode } from 'react'
import { Link } from 'react-router-dom'
import { AlertTriangle, ArrowDownRight, ArrowRight, ArrowUpRight, BarChart3, Database, Gauge } from 'lucide-react'
import { EmptyState, PageHeader } from './components/Shell'
import { useApp } from './context/AppContext'
import { useIntelligence } from './context/IntelligenceContext'
import { dateRangeForPreset, type DatePreset, type MetricValue } from './lib/metrics'
import { AcquireRegistryPage } from './release2Pages'
import { BuyerRecoveryPerformance,ProgramRecoveryPerformance } from './recoveryPages'

const number = new Intl.NumberFormat('en-US', { maximumFractionDigits: 1 })
const money = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 })
const datePresets: { value: DatePreset; label: string }[] = [{ value: 'today', label: 'Today' },{ value: 'yesterday', label: 'Yesterday' },{ value: 'last_7_days', label: 'Last 7 Days' },{ value: 'last_30_days', label: 'Last 30 Days' },{ value: 'this_month', label: 'This Month' },{ value: 'last_month', label: 'Last Month' },{ value: 'custom', label: 'Custom' }]

function formatMetric(value: number | null, format: 'number' | 'percent' | 'time' | 'money' = 'number') {
  if (value == null) return 'Unavailable'
  if (format === 'percent') return `${number.format(value)}%`
  if (format === 'time') return value >= 1000 ? `${number.format(value / 1000)} s` : `${number.format(value)} ms`
  if (format === 'money') return money.format(value)
  return number.format(value)
}

export function IntelligenceFilterBar() {
  const { data, tenant } = useApp(); const { filters, setFilters } = useIntelligence()
  const update = (key: keyof typeof filters, value: string) => { const next = { ...filters, [key]: value }; if (key === 'preset' && value !== 'custom') { const range = dateRangeForPreset(value as DatePreset); next.start = range.start.slice(0, 10); next.end = range.end.slice(0, 10) } setFilters(next) }
  const sources = data.trafficSources.filter((row) => row.tenantId === tenant.id); const campaigns = data.campaigns.filter((row) => row.tenantId === tenant.id); const buyers = data.buyers.filter((row) => row.tenantId === tenant.id); const programs = data.programs.filter((row) => row.tenantId === tenant.id); const offers = data.offers.filter((row) => row.tenantId === tenant.id)
  return <section className="intelligence-filters" aria-label="Intelligence filters"><div className="filter-heading"><span>Intelligence scope</span><small>Filters persist across intelligence views</small></div><div className="filter-grid"><label>Date range<select value={filters.preset} onChange={(event) => update('preset', event.target.value)}>{datePresets.map((preset) => <option key={preset.value} value={preset.value}>{preset.label}</option>)}</select></label>{filters.preset === 'custom' && <><label>Start<input type="date" value={filters.start} onChange={(event) => update('start', event.target.value)} /></label><label>End<input type="date" value={filters.end} onChange={(event) => update('end', event.target.value)} /></label></>}<FilterSelect label="Source" value={filters.trafficSourceId} onChange={(value) => update('trafficSourceId', value)} options={sources.map((row) => ({ id: row.id, label: row.name }))} /><FilterSelect label="Campaign" value={filters.campaignId} onChange={(value) => update('campaignId', value)} options={campaigns.map((row) => ({ id: row.id, label: row.name }))} /><FilterSelect label="Buyer" value={filters.buyerId} onChange={(value) => update('buyerId', value)} options={buyers.map((row) => ({ id: row.id, label: row.name }))} /><FilterSelect label="Program" value={filters.programId} onChange={(value) => update('programId', value)} options={programs.map((row) => ({ id: row.id, label: row.name }))} /><FilterSelect label="Offer" value={filters.offerId} onChange={(value) => update('offerId', value)} options={offers.map((row) => ({ id: row.id, label: row.name }))} /><FilterSelect label="Lead status" value={filters.leadStatus} onChange={(value) => update('leadStatus', value)} options={['new','validated','queued','delivering','accepted','rejected','recovered','closed'].map((value) => ({ id: value, label: value }))} /></div></section>
}

function FilterSelect({ label, value, options, onChange }: { label: string; value: string; options: { id: string; label: string }[]; onChange: (value: string) => void }) { return <label>{label}<select value={value} onChange={(event) => onChange(event.target.value)}><option value="">All</option>{options.map((option) => <option key={option.id} value={option.id}>{option.label}</option>)}</select></label> }

function IntelligenceState({ children }: { children: (report: NonNullable<ReturnType<typeof useIntelligence>['report']>) => ReactNode }) { const { report, loading, error } = useIntelligence(); if (loading && !report) return <section className="panel intelligence-loading"><div className="loader" /><p>Calculating tenant intelligence…</p></section>; if (error) return <section className="panel intelligence-loading"><AlertTriangle /><p>{error}</p></section>; if (!report) return <EmptyState title="No intelligence available" description="No operational intelligence could be calculated for this period." />; return <>{children(report)}</> }

function MetricCard({ label, metric, format = 'number', detail }: { label: string; metric: MetricValue; format?: 'number' | 'percent' | 'time' | 'money'; detail?: string }) { const positive = (metric.change ?? 0) >= 0; return <article className="intelligence-kpi"><span>{label}</span><strong className={metric.value == null ? 'unavailable' : ''}>{formatMetric(metric.value, format)}</strong>{metric.change == null ? <small>{detail ?? 'No comparable prior-period data'}</small> : <small className={positive ? 'trend-positive' : 'trend-negative'}>{positive ? <ArrowUpRight size={13} /> : <ArrowDownRight size={13} />}{number.format(Math.abs(metric.change))}{metric.changeKind === 'points' ? ' pts' : '%'} vs prior period</small>}</article> }

function KpiGrid({ children }: { children: ReactNode }) { return <section className="intelligence-kpis">{children}</section> }

function TrendChart({ points }: { points: { label: string; leads: number; accepted: number; rejected: number }[] }) { if (!points.length) return <EmptyState title="No lead activity for this period" description="Trend lines will appear when lead activity is recorded." />; const max = Math.max(1, ...points.map((row) => row.leads)); const coords = (key: 'leads' | 'accepted' | 'rejected') => points.map((row, index) => `${points.length === 1 ? 50 : (index / (points.length - 1)) * 100},${94 - (row[key] / max) * 80}`).join(' '); return <div className="trend-wrap"><svg className="trend-chart" viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label="Lead volume, acceptance, and rejection trend"><line x1="0" y1="94" x2="100" y2="94" /><polyline className="trend-leads" points={coords('leads')} /><polyline className="trend-accepted" points={coords('accepted')} /><polyline className="trend-rejected" points={coords('rejected')} /></svg><div className="chart-legend"><span className="legend-leads">Leads</span><span className="legend-accepted">Accepted</span><span className="legend-rejected">Rejected</span></div><div className="trend-axis"><span>{points[0].label.slice(5)}</span><span>{points.at(-1)?.label.slice(5)}</span></div></div> }

function BarList({ items, empty = 'No data available.' }: { items: { label: string; count: number; secondary?: string }[]; empty?: string }) { if (!items.length) return <EmptyState title={empty} description="Data will appear when qualifying activity is recorded." />; const max = Math.max(...items.map((item) => item.count), 1); return <div className="metric-bars">{items.map((item) => <div key={item.label}><div><strong>{item.label}</strong><span>{item.secondary ?? number.format(item.count)}</span></div><i><b style={{ width: `${(item.count / max) * 100}%` }} /></i></div>)}</div> }

export function IntelligenceOverviewPage() { const { data } = useApp(); return <><PageHeader eyebrow="Axis Intelligence · Release 4" title={`Good afternoon, ${data.user.name.split(' ')[0]}`} description="Connect acquisition, delivery, CRM outcomes, and economic value across the lead lifecycle." action={<Link className="primary-button" to="/integrations"><BarChart3 size={16} /> Integration health</Link>} /><IntelligenceFilterBar /><IntelligenceState>{(report) => <><KpiGrid><MetricCard label="Total Leads" metric={report.kpis.totalLeads} /><MetricCard label="Accepted Leads" metric={report.kpis.acceptedLeads} /><MetricCard label="Conversions" metric={report.outcomes.conversions} /><MetricCard label="Outcome Revenue" metric={report.outcomes.revenue} format="money" /><MetricCard label="Revenue / Lead" metric={report.outcomes.revenuePerLead} format="money" /><MetricCard label="Revenue / Accepted" metric={report.outcomes.revenuePerAcceptedLead} format="money" /><MetricCard label="Acceptance Rate" metric={report.kpis.acceptanceRate} format="percent" /><MetricCard label="Recovery Opportunity" metric={report.kpis.recoveryOpportunity} /></KpiGrid><section className="panel outcome-section"><PanelHeading title="Closed-loop outcome funnel" detail="Downstream events explicitly mapped from trusted CRM sources" /><div className="outcome-funnel">{report.outcomes.funnel.map((stage) => <div key={stage.key}><span>{stage.label}</span><strong>{number.format(stage.count)}</strong></div>)}</div></section><div className="intelligence-layout"><section className="panel chart-panel"><PanelHeading title="Lead volume and delivery outcomes" detail="Daily activity in the selected period" /><TrendChart points={report.trends} /></section><section className="panel"><PanelHeading title="Lead funnel" detail="Observed operational stages only" /><div className="funnel">{report.funnel.map((stage, index) => <div key={stage.key}><span>{stage.label}</span><strong>{number.format(stage.count)}</strong><small>{index ? `${formatMetric(stage.conversion, 'percent')} of received · ${formatMetric(stage.dropoff, 'percent')} drop-off` : 'Selected-period intake'}</small></div>)}</div></section></div><DataQuality report={report} /></>}</IntelligenceState></> }

function PanelHeading({ title, detail, action }: { title: string; detail: string; action?: ReactNode }) { return <div className="panel-heading"><div><h2>{title}</h2><p>{detail}</p></div>{action}</div> }
function DataQuality({ report }: { report: NonNullable<ReturnType<typeof useIntelligence>['report']> }) { const total = Object.values(report.dataQuality).reduce((sum, value) => sum + value, 0); if (!total) return null; return <section className="data-quality"><Database size={17} /><div><strong>Data-quality visibility</strong><span>{report.dataQuality.missingSource} missing source · {report.dataQuality.missingCampaign} missing campaign · {report.dataQuality.missingProgram} missing program · {report.dataQuality.missingResponseTime} missing response time · {report.dataQuality.unknownRejectionReason} unclassified rejections</span></div></section> }

export function AcquireIntelligencePage() { return <><PageHeader eyebrow="Axis Acquire · Intelligence" title="Source performance" description="Compare acquisition quality using delivery, conversion, and economic outcomes." /><IntelligenceFilterBar /><IntelligenceState>{(report) => <section className="panel table-panel intelligence-section"><PanelHeading title="Source and campaign intelligence" detail="Closed-loop value is attributed only through matched outcome records" /><PerformanceTable rows={report.sources.map((row) => ({ id: `${row.sourceId}-${row.campaignId}`, cells: [row.source,row.campaign,number.format(row.leads),number.format(row.accepted),number.format(row.rejected),formatMetric(row.acceptanceRate,'percent'),number.format(row.conversions),formatMetric(row.outcomeRevenue,'money'),formatMetric(row.averageResponseMs,'time')] }))} headers={['Traffic Source','Campaign','Leads','Accepted','Rejected','Acceptance Rate','Conversions','Outcome Revenue','Avg. Response']} empty="No source performance for this period." /></section>}</IntelligenceState><div className="embedded-registry"><AcquireRegistryPage embedded /></div></> }

export function ConvertIntelligencePage() { return <FoundationPage eyebrow="Axis Convert · Intelligence" title="Lead quality signals" description="Connect validation and quality signals to downstream acceptance without inventing landing-page conversion data.">{(report) => <><KpiGrid><MetricCard label="Lead Volume" metric={report.kpis.totalLeads} /><MetricCard label="Validated Leads" metric={{ ...report.kpis.totalLeads, value: report.funnel[1]?.count ?? 0 }} /><MetricCard label="Validation Rate" metric={{ ...report.kpis.acceptanceRate, value: report.funnel[1]?.conversion ?? null }} format="percent" /><MetricCard label="Acceptance Rate" metric={report.kpis.acceptanceRate} format="percent" /></KpiGrid><section className="panel"><PanelHeading title="Program mix" detail="Lead volume by assigned program" /><BarList items={report.programs.map((row) => ({ label: row.program, count: row.leads, secondary: `${formatMetric(row.acceptanceRate,'percent')} accepted` }))} empty="No program mix available." /></section></>}</FoundationPage> }

export function RouteIntelligencePage() { const { data, tenant } = useApp(); return <FoundationPage eyebrow="Axis Route · Intelligence" title="Delivery operations" description="Monitor throughput, buyer response, rejection pressure, and available capacity.">{(report) => <><KpiGrid><MetricCard label="Leads Awaiting Delivery" metric={{ ...report.kpis.totalLeads, value: data.leads.filter((row) => row.tenantId === tenant.id && ['queued','delivering'].includes(row.status)).length }} /><MetricCard label="Delivery Attempts" metric={{ ...report.kpis.totalLeads, value: report.buyers.reduce((sum, row) => sum + row.attempted, 0) }} /><MetricCard label="Acceptance Rate" metric={report.kpis.acceptanceRate} format="percent" /><MetricCard label="Rejection Rate" metric={report.kpis.rejectionRate} format="percent" /><MetricCard label="Timeout Rate" metric={report.kpis.timeoutRate} format="percent" /><MetricCard label="Average Response" metric={report.kpis.averageResponseMs} format="time" /></KpiGrid><div className="intelligence-layout"><section className="panel"><PanelHeading title="Buyer capacity" detail="Current configured allocations" action={<Link className="text-button" to="/intelligence/buyers">Full scorecard <ArrowRight size={14} /></Link>} /><CapacityTable rows={report.buyers} /></section><section className="panel"><PanelHeading title="Top rejection reasons" detail="Structured delivery outcomes" /><BarList items={report.rejectionCategories.map((row) => ({ label: row.label, count: row.count, secondary: `${row.recoverable} recoverable` }))} empty="No rejection data available." /></section></div></>}</FoundationPage> }

export function RecoverIntelligencePage() { return <FoundationPage eyebrow="Axis Recover · Intelligence" title="Recovery opportunity" description="Identify rejected volume that may be recoverable. No leads are rerouted automatically.">{(report) => <><KpiGrid><MetricCard label="Rejected Leads" metric={report.kpis.rejectedLeads} /><MetricCard label="Recoverable Leads" metric={report.kpis.recoveryOpportunity} /><MetricCard label="Recovery Opportunity %" metric={metricFromRatio(report.kpis.recoveryOpportunity.value, report.kpis.rejectedLeads.value)} format="percent" /></KpiGrid><div className="intelligence-layout"><section className="panel"><PanelHeading title="Recoverable categories" detail="Structured reasons marked recoverable" /><BarList items={report.rejectionCategories.filter((row) => row.recoverable).map((row) => ({ label: row.label, count: row.recoverable }))} empty="No recoverable rejection data available." /></section><section className="panel"><PanelHeading title="Programs with opportunity" detail="Recoverable rejected leads by program" /><BarList items={report.recoverablePrograms} empty="No program recovery opportunity." /></section></div></>}</FoundationPage> }

export function OptimizeIntelligencePage() { return <FoundationPage eyebrow="Axis Optimize · Intelligence" title="Executive analytical workspace" description="Consolidated operating indicators for deliberate, human-led optimization.">{(report) => <><KpiGrid><MetricCard label="Lead Volume" metric={report.kpis.totalLeads} /><MetricCard label="Acceptance Rate" metric={report.kpis.acceptanceRate} format="percent" /><MetricCard label="Capacity Utilization" metric={report.kpis.capacityUtilization} format="percent" /><MetricCard label="Recovery Opportunity" metric={report.kpis.recoveryOpportunity} /><MetricCard label="Response Time" metric={report.kpis.averageResponseMs} format="time" /></KpiGrid><div className="intelligence-layout"><section className="panel"><PanelHeading title="Source performance" detail="Highest-volume acquisition paths" /><BarList items={report.sources.slice(0, 6).map((row) => ({ label: `${row.source} · ${row.campaign}`, count: row.leads, secondary: `${formatMetric(row.acceptanceRate,'percent')} accepted` }))} /></section><section className="panel"><PanelHeading title="Buyer performance" detail="Delivery attempts and acceptance" /><BarList items={report.buyers.slice(0, 6).map((row) => ({ label: row.buyer, count: row.attempted, secondary: `${formatMetric(row.acceptanceRate,'percent')} accepted` }))} /></section></div><section className="panel future-panel"><Gauge size={21} /><div><h2>Recommendations require more intelligence</h2><p>Optimization recommendations will become available as Axis accumulates sufficient operational intelligence. Release 3 does not generate or execute automated recommendations.</p></div></section></>}</FoundationPage> }

export function BuyerIntelligencePage() { return <><FoundationPage eyebrow="Intelligence · Buyers" title="Buyer scorecard" description="Compare delivery quality, downstream outcomes, economic value, and capacity.">{(report) => <section className="panel table-panel"><PerformanceTable headers={['Buyer','Attempted','Accepted','Acceptance Rate','Qualified','Apps / Sales','Conversions','Starts / Completions','Outcome Revenue','Revenue / Lead','Utilization','Top Rejection']} rows={report.buyers.map((row) => ({ id: row.buyerId, cells: [<Link className="text-button" to={`/buyers-offers/buyers/${row.buyerId}`}>{row.buyer}</Link>,row.attempted,row.accepted,formatMetric(row.acceptanceRate,'percent'),row.qualifiedOutcomes,row.applicationsSales,row.conversions,row.startsCompletions,formatMetric(row.outcomeRevenue,'money'),formatMetric(row.revenuePerLead,'money'),<span className={`capacity-state capacity-${row.capacityStatus}`}>{formatMetric(row.utilization,'percent')} · {row.capacityStatus.replace('_',' ')}</span>,row.topRejectionReason] }))} empty="No buyer activity for this period." /></section>}</FoundationPage><BuyerRecoveryPerformance/></> }

export function ProgramIntelligencePage() { return <><FoundationPage eyebrow="Intelligence · Programs" title="Program performance" description="Understand program demand, buyer participation, downstream outcomes, and economic value.">{(report) => <section className="panel table-panel"><PerformanceTable headers={['Program','Leads','Attempts','Accepted','Rejected','Acceptance Rate','Conversions','Outcome Revenue','Active Buyers','Remaining Capacity','Top Rejection']} rows={report.programs.map((row) => ({ id: row.programId, cells: [row.program,row.leads,row.attempts,row.accepted,row.rejected,formatMetric(row.acceptanceRate,'percent'),row.conversions,formatMetric(row.outcomeRevenue,'money'),row.activeBuyers,row.remainingCapacity,row.topRejectionReason] }))} empty="No program activity for this period." /></section>}</FoundationPage><ProgramRecoveryPerformance/></> }

export function RejectionIntelligencePage() { return <FoundationPage eyebrow="Intelligence · Rejections" title="Rejection intelligence" description="See why lead value is lost and which outcomes may be recoverable.">{(report) => <><KpiGrid><MetricCard label="Total Rejections" metric={report.kpis.rejectedLeads} /><MetricCard label="Rejection Rate" metric={report.kpis.rejectionRate} format="percent" /><MetricCard label="Recoverable Rejections" metric={report.kpis.recoveryOpportunity} /><MetricCard label="Recoverable %" metric={metricFromRatio(report.kpis.recoveryOpportunity.value, report.kpis.rejectedLeads.value)} format="percent" /></KpiGrid><div className="intelligence-layout"><section className="panel"><PanelHeading title="Top rejection categories" detail="Unknown reasons remain visible" /><BarList items={report.rejectionCategories.map((row) => ({ label: row.label, count: row.count, secondary: `${row.recoverable} recoverable` }))} empty="No rejection data available." /></section><section className="panel"><PanelHeading title="Buyers by rejections" detail="Structured rejections in this period" /><BarList items={report.rejectionBuyers} empty="No buyer rejection data." /></section></div><section className="panel"><PanelHeading title="Programs by rejections" detail="Drill into program and lead records through operational views" /><BarList items={report.rejectionPrograms} empty="No program rejection data." /></section></>}</FoundationPage> }

function FoundationPage({ eyebrow, title, description, children }: { eyebrow: string; title: string; description: string; children: (report: NonNullable<ReturnType<typeof useIntelligence>['report']>) => ReactNode }) { return <><PageHeader eyebrow={eyebrow} title={title} description={description} /><IntelligenceFilterBar /><IntelligenceState>{children}</IntelligenceState></> }
function metricFromRatio(part: number | null, total: number | null): MetricValue { return { value: part != null && total ? (part / total) * 100 : null, previous: null, change: null, changeKind: 'points' } }
function PerformanceTable({ headers, rows, empty }: { headers: string[]; rows: { id: string; cells: ReactNode[] }[]; empty: string }) { if (!rows.length) return <EmptyState title={empty} description="Adjust the filters or wait for operational activity." />; return <div className="table-scroll"><table><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.id}>{row.cells.map((cell, index) => <td key={`${row.id}-${headers[index]}`}>{cell}</td>)}</tr>)}</tbody></table></div> }
function CapacityTable({ rows }: { rows: NonNullable<ReturnType<typeof useIntelligence>['report']>['buyers'] }) { if (!rows.some((row) => row.cap)) return <EmptyState title="No capacity configured" description="Configure buyer caps to unlock utilization intelligence." />; return <div className="capacity-intelligence">{rows.filter((row) => row.cap).map((row) => <div key={row.buyerId}><div><strong>{row.buyer}</strong><span>{row.delivered} / {row.cap} delivered</span></div><div className="capacity-track"><i style={{ width: `${Math.min(100, row.utilization ?? 0)}%` }} /></div><small className={`capacity-state capacity-${row.capacityStatus}`}>{formatMetric(row.utilization,'percent')} · {row.capacityStatus.replace('_',' ')}</small></div>)}</div> }
