import { useMemo, useState, type FormEvent } from 'react'
import { Link, Navigate, useParams } from 'react-router-dom'
import { AlertTriangle, ArrowLeft, ArrowRight, BarChart3, Building2, CheckCircle2, Clock3, GitBranch, Layers3, LockKeyhole, Plus, Search, Send, Target, XCircle } from 'lucide-react'
import { EmptyState, PageHeader, Status } from './components/Shell'
import { FormField, Modal } from './components/Modal'
import { useApp } from './context/AppContext'
import { useIntelligence } from './context/IntelligenceContext'
import { platformService } from './services/platformService'
import type { Campaign, LeadStatus, TrafficSource } from './types'
import { RecoveryJourneyPanel } from './recoveryPages'

const formatDate = (value: string | null) => value ? new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' }).format(new Date(value)) : '—'
const formatMoney = (value: number, currency = 'USD') => new Intl.NumberFormat('en-US', { style: 'currency', currency, maximumFractionDigits: 0 }).format(value)
const percent = (delivered: number, limit: number) => limit ? Math.min(100, Math.round((delivered / limit) * 100)) : 0

export function Release2OverviewPage() {
  const { data, tenant } = useApp()
  const leads = data.leads.filter((item) => item.tenantId === tenant.id)
  const attempts = data.deliveryAttempts.filter((item) => item.tenantId === tenant.id)
  const buyers = data.buyers.filter((item) => item.tenantId === tenant.id)
  const caps = data.buyerCaps.filter((item) => item.tenantId === tenant.id)
  const stats = [
    { label: 'Operational leads', value: leads.length, detail: `${leads.filter((item) => item.status === 'accepted').length} accepted`, icon: Target },
    { label: 'Delivery attempts', value: attempts.length, detail: `${attempts.filter((item) => item.status === 'rejected').length} rejected`, icon: Send },
    { label: 'Active buyers', value: buyers.filter((item) => item.status === 'active').length, detail: `${data.buyerPrograms.length} program mappings`, icon: Building2 },
    { label: 'Capacity remaining', value: caps.reduce((sum, cap) => sum + Math.max(0, cap.limit - cap.delivered), 0), detail: `${caps.length} active caps`, icon: Layers3 },
  ]
  return <>
    <PageHeader eyebrow="Axis Lead Ecosystem" title={`Good afternoon, ${data.user.name.split(' ')[0]}`} description="A tenant-safe view of acquisition context, buyer capacity, and lead delivery outcomes." action={<Link className="primary-button" to="/route"><GitBranch size={16} /> Open Route</Link>} />
    <section className="stat-grid">{stats.map(({ icon: Icon, ...item }) => <article className="stat-card" key={item.label}><div className="stat-top"><span>{item.label}</span><Icon size={18} /></div><strong>{item.value}</strong><small>{item.detail}</small></article>)}</section>
    <div className="detail-grid"><section className="panel table-panel"><div className="panel-heading"><div><h2>Recent lead journeys</h2><p>Identity-free operational activity</p></div><Link className="text-button" to="/leads">Open registry <ArrowRight size={14} /></Link></div>{leads.length ? <div className="table-scroll"><table><thead><tr><th>Lead</th><th>Campaign</th><th>Program</th><th>Status</th><th>Attempts</th></tr></thead><tbody>{leads.slice(0, 6).map((lead) => <tr key={lead.id}><td><Link className="text-button mono" to={`/leads/${lead.id}`}>{lead.reference}</Link></td><td>{lead.campaign}</td><td>{lead.program}</td><td><Status value={lead.status} /></td><td>{attempts.filter((item) => item.leadId === lead.id).length}</td></tr>)}</tbody></table></div> : <EmptyState title="No leads yet" description="New tenants begin with an empty operational registry." />}</section><section className="panel"><div className="panel-heading"><div><h2>Lead ecosystem readiness</h2><p>Lead ecosystem foundations</p></div></div><div className="readiness-list"><div className="readiness"><span><Target size={18} /></span><div><strong>Acquisition context</strong><small>{data.trafficSources.length} sources · {data.campaigns.length} campaigns</small></div><CheckCircle2 className="check" size={18} /></div><div className="readiness"><span><Building2 size={18} /></span><div><strong>Buyer eligibility</strong><small>{data.buyerPrograms.length} active relationships</small></div><CheckCircle2 className="check" size={18} /></div><div className="readiness"><span><GitBranch size={18} /></span><div><strong>Delivery history</strong><small>Multiple attempts preserved per lead</small></div><CheckCircle2 className="check" size={18} /></div><div className="readiness"><span><LockKeyhole size={18} /></span><div><strong>PII boundary</strong><small>Identity remains separately authorized</small></div><CheckCircle2 className="check" size={18} /></div></div></section></div>
  </>
}

export function AcquireRegistryPage({ embedded = false }: { embedded?: boolean }) {
  const { data, tenant, allowed, refresh } = useApp()
  const [tab, setTab] = useState<'sources' | 'campaigns'>('sources')
  const [editing, setEditing] = useState<TrafficSource | Campaign | null | undefined>(undefined)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const writable = allowed('source:write')
  async function save(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setError('')
    const form = new FormData(event.currentTarget)
    try {
      if (tab === 'sources') await platformService.saveTrafficSource({ id: (editing as TrafficSource | null)?.id, tenantId: tenant.id, name: String(form.get('name')).trim(), sourceType: String(form.get('sourceType')).trim(), externalId: String(form.get('externalId')).trim(), status: String(form.get('status')) as TrafficSource['status'], notes: String(form.get('notes')).trim() })
      else await platformService.saveCampaign({ id: (editing as Campaign | null)?.id, tenantId: tenant.id, trafficSourceId: String(form.get('trafficSourceId')) || null, name: String(form.get('name')).trim(), externalId: String(form.get('externalId')).trim(), status: String(form.get('status')) as Campaign['status'], campaignType: String(form.get('campaignType')).trim(), startDate: String(form.get('startDate')) || null, endDate: String(form.get('endDate')) || null })
      await refresh(); setEditing(undefined)
    } catch { setError('The registry record could not be saved. Verify tenant relationships and unique names.') }
    finally { setBusy(false) }
  }
  const items = tab === 'sources' ? data.trafficSources : data.campaigns
  return <>
    {!embedded && <PageHeader eyebrow="Axis Acquire" title="Acquisition registry" description="Connect traffic sources and campaigns to the operational lead journey." action={writable ? <button className="primary-button" onClick={() => setEditing(null)}><Plus size={17} /> Add {tab === 'sources' ? 'source' : 'campaign'}</button> : undefined} />}
    {embedded && <div className="panel-heading embedded-heading"><div><h2>Acquisition registry</h2><p>Manage tenant-scoped sources and campaigns</p></div>{writable && <button className="primary-button" onClick={() => setEditing(null)}><Plus size={17} /> Add {tab === 'sources' ? 'source' : 'campaign'}</button>}</div>}
    <div className="tabs"><button className={tab === 'sources' ? 'active' : ''} onClick={() => { setTab('sources'); setEditing(undefined) }}>Traffic sources <b>{data.trafficSources.length}</b></button><button className={tab === 'campaigns' ? 'active' : ''} onClick={() => { setTab('campaigns'); setEditing(undefined) }}>Campaigns <b>{data.campaigns.length}</b></button></div>
    <section className="panel table-panel">{items.length ? <div className="table-scroll"><table><thead><tr><th>Name</th><th>{tab === 'sources' ? 'Source type' : 'Traffic source'}</th><th>External ID</th><th>Status</th>{tab === 'campaigns' && <th>Flight</th>}</tr></thead><tbody>{tab === 'sources' ? data.trafficSources.map((source) => <tr key={source.id}><td>{writable ? <button className="text-button" onClick={() => setEditing(source)}>{source.name}</button> : <strong>{source.name}</strong>}<small className="cell-sub">{source.notes || 'No notes'}</small></td><td>{source.sourceType}</td><td className="mono">{source.externalId || '—'}</td><td><Status value={source.status} /></td></tr>) : data.campaigns.map((campaign) => <tr key={campaign.id}><td>{writable ? <button className="text-button" onClick={() => setEditing(campaign)}>{campaign.name}</button> : <strong>{campaign.name}</strong>}<small className="cell-sub">{campaign.campaignType || 'General campaign'}</small></td><td>{data.trafficSources.find((source) => source.id === campaign.trafficSourceId)?.name ?? 'Unassigned'}</td><td className="mono">{campaign.externalId || '—'}</td><td><Status value={campaign.status} /></td><td>{campaign.startDate ?? 'Open'} → {campaign.endDate ?? 'Ongoing'}</td></tr>)}</tbody></table></div> : <EmptyState title={tab === 'sources' ? 'No traffic sources configured' : 'No campaigns configured'} description={tab === 'sources' ? 'Add the first source for this tenant.' : 'Add the first campaign for this tenant.'} />}</section>
    {editing !== undefined && <Modal title={`${editing ? 'Edit' : 'Create'} ${tab === 'sources' ? 'traffic source' : 'campaign'}`} description="This operational registry record is scoped to the active tenant." error={error} busy={busy} onClose={() => setEditing(undefined)} onSubmit={(event) => void save(event)}><FormField label="Name"><input name="name" required defaultValue={editing?.name} /></FormField>{tab === 'sources' ? <><FormField label="Source type"><input name="sourceType" required list="source-types" defaultValue={(editing as TrafficSource | null)?.sourceType} /><datalist id="source-types"><option value="meta" /><option value="google" /><option value="tiktok" /><option value="affiliate" /><option value="organic" /><option value="email" /><option value="referral" /><option value="other" /></datalist></FormField><FormField label="Notes"><textarea name="notes" rows={3} defaultValue={(editing as TrafficSource | null)?.notes} /></FormField></> : <><FormField label="Traffic source"><select name="trafficSourceId" defaultValue={(editing as Campaign | null)?.trafficSourceId ?? ''}><option value="">Unassigned</option>{data.trafficSources.map((source) => <option value={source.id} key={source.id}>{source.name}</option>)}</select></FormField><FormField label="Campaign type"><input name="campaignType" defaultValue={(editing as Campaign | null)?.campaignType} /></FormField><div className="form-grid"><FormField label="Start date"><input type="date" name="startDate" defaultValue={(editing as Campaign | null)?.startDate ?? ''} /></FormField><FormField label="End date"><input type="date" name="endDate" defaultValue={(editing as Campaign | null)?.endDate ?? ''} /></FormField></div></>}<FormField label="External identifier"><input name="externalId" defaultValue={(editing as TrafficSource | Campaign | null)?.externalId} /></FormField><FormField label="Status"><select name="status" defaultValue={editing?.status ?? 'active'}><option value="active">Active</option><option value="paused">Paused</option><option value="draft">Draft</option><option value="inactive">Inactive</option></select></FormField></Modal>}
  </>
}

export function LeadEcosystemPage() {
  const { data, tenant } = useApp()
  const [query, setQuery] = useState('')
  const [status, setStatus] = useState<'all' | LeadStatus>('all')
  const leads = useMemo(() => data.leads.filter((lead) => lead.tenantId === tenant.id && (status === 'all' || lead.status === status) && `${lead.reference} ${lead.program} ${lead.source} ${lead.campaign}`.toLowerCase().includes(query.toLowerCase())), [data.leads, query, status, tenant.id])
  return <>
    <PageHeader eyebrow="Lead ecosystem" title="Leads" description="Operational lead records with source, campaign, lifecycle, and delivery history." />
    <div className="info-banner"><LockKeyhole size={18} /><div><strong>PII remains isolated</strong><span>This registry uses operational identifiers. Identity is loaded only for directly authorized roles.</span></div></div>
    <section className="panel table-panel"><div className="toolbar"><div className="search-field"><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search lead, program, source, or campaign" aria-label="Search leads" /></div><select className="inline-select" value={status} onChange={(event) => setStatus(event.target.value as typeof status)} aria-label="Filter lead status"><option value="all">All statuses</option>{['new','validated','queued','delivering','accepted','rejected','recovered','closed'].map((value) => <option value={value} key={value}>{value}</option>)}</select></div>{leads.length ? <div className="table-scroll"><table><thead><tr><th>Lead</th><th>Source / campaign</th><th>Program / offer</th><th>Score</th><th>Status</th><th>Attempts</th><th>Received</th></tr></thead><tbody>{leads.map((lead) => <tr key={lead.id}><td><Link className="text-button mono" to={`/leads/${lead.id}`}>{lead.reference} <ArrowRight size={13} /></Link><small className="cell-sub mono">{lead.externalLeadId || 'No external ID'}</small></td><td><strong>{lead.source}</strong><small className="cell-sub">{lead.campaign}</small></td><td><strong>{lead.program}</strong><small className="cell-sub">{lead.offer}</small></td><td><span className="score">{lead.score}</span></td><td><Status value={lead.status} /></td><td>{data.deliveryAttempts.filter((attempt) => attempt.leadId === lead.id).length}</td><td>{formatDate(lead.receivedAt)}</td></tr>)}</tbody></table></div> : <EmptyState title="No matching leads" description="Adjust the filters or wait for operational lead intake." />}</section>
  </>
}

export function LeadDetailPage() {
  const { leadId } = useParams()
  const { data, tenant, allowed } = useApp()
  const lead = data.leads.find((item) => item.id === leadId && item.tenantId === tenant.id)
  if (!lead) return <Navigate to="/leads" replace />
  const attempts = data.deliveryAttempts.filter((item) => item.leadId === lead.id).sort((a, b) => a.attemptNumber - b.attemptNumber)
  const rejections = data.leadRejections.filter((item) => item.leadId === lead.id)
  const statuses = data.leadStatusHistory.filter((item) => item.leadId === lead.id)
  const identity = allowed('lead:identity:read') ? data.leadIdentities.find((item) => item.leadId === lead.id) : undefined
  const outcomes = data.leadOutcomes.filter((item) => item.leadId === lead.id)
  const journey = [...statuses.map((event) => ({ id: event.id, time: event.createdAt, kind: 'status' as const, title: event.toStatus, detail: event.reason || `Status changed from ${event.fromStatus ?? 'created'}` })), ...attempts.map((attempt) => { const buyer = data.buyers.find((item) => item.id === attempt.buyerId); const rejection = rejections.find((item) => item.deliveryAttemptId === attempt.id); return { id: attempt.id, time: attempt.createdAt, kind: 'delivery' as const, title: `${buyer?.name ?? 'Buyer'} attempt ${attempt.attemptNumber}`, detail: rejection ? `${attempt.status} — ${rejection.reason}` : attempt.status } }), ...outcomes.map((outcome) => ({ id:outcome.id,time:outcome.occurredAt,kind:'outcome' as const,title:outcome.outcomeType,detail:`${outcome.sourceSystem} · ${outcome.outcomeStage}${outcome.monetaryValue == null ? '' : ` · ${formatMoney(outcome.monetaryValue,outcome.currency)}`}` }))].sort((a, b) => new Date(a.time).getTime() - new Date(b.time).getTime())
  return <>
    <Link className="back-link" to="/leads"><ArrowLeft size={15} /> Back to leads</Link>
    <PageHeader eyebrow="Lead detail" title={lead.reference} description="Identity-safe operational journey and buyer delivery history." action={<Status value={lead.status} />} />
    <div className="detail-grid"><section className="panel"><div className="panel-heading"><div><h2>Overview</h2><p>Operational context</p></div></div><dl className="detail-list"><div><dt>Source</dt><dd>{lead.source}</dd></div><div><dt>Campaign</dt><dd>{lead.campaign}</dd></div><div><dt>Program</dt><dd>{lead.program}</dd></div><div><dt>Offer</dt><dd>{lead.offer}</dd></div><div><dt>Quality score</dt><dd><span className="score">{lead.score}</span></dd></div><div><dt>Received</dt><dd>{formatDate(lead.receivedAt)}</dd></div></dl></section><section className="panel"><div className="panel-heading"><div><h2>Identity</h2><p>Least-privilege view</p></div><LockKeyhole size={18} /></div>{identity ? <dl className="detail-list"><div><dt>Name</dt><dd>{identity.displayName}</dd></div><div><dt>Email</dt><dd>{identity.email}</dd></div><div><dt>Phone</dt><dd>{identity.phone}</dd></div><div><dt>Protection</dt><dd>Masked where appropriate</dd></div></dl> : <EmptyState title="Identity access restricted" description="Your current role can use the operational lead record without viewing PII." />}</section></div>
     <section className="panel journey-panel"><div className="panel-heading"><div><h2>Lead journey</h2><p>Axis lifecycle, delivery, external CRM, and economic outcomes in sequence</p></div></div>{journey.length ? <ol className="timeline">{journey.map((event) => <li key={`${event.kind}-${event.id}`} className={`timeline-${event.kind}`}><span>{event.kind === 'delivery' ? <Send size={15} /> : event.kind === 'outcome' ? <BarChart3 size={15}/> : <CheckCircle2 size={15} />}</span><div><strong>{event.title}</strong><p>{event.detail}</p></div><time>{formatDate(event.time)}</time></li>)}</ol> : <EmptyState title="No journey events" description="Lifecycle events will appear as this lead progresses." />}</section><RecoveryJourneyPanel leadId={lead.id}/>
    <div className="detail-grid"><section className="panel table-panel"><div className="panel-heading"><div><h2>Delivery attempts</h2><p>Full buyer interaction history</p></div></div>{attempts.length ? <div className="table-scroll"><table><thead><tr><th>#</th><th>Buyer</th><th>Method</th><th>Status</th><th>Response</th><th>Payout</th></tr></thead><tbody>{attempts.map((attempt) => { const buyer = data.buyers.find((item) => item.id === attempt.buyerId); return <tr key={attempt.id}><td>{attempt.attemptNumber}</td><td><Link className="text-button" to={`/buyers-offers/buyers/${attempt.buyerId}`}>{buyer?.name ?? 'Unknown'}</Link></td><td>{attempt.deliveryMethod}</td><td><Status value={attempt.status} /></td><td>{attempt.responseTimeMs == null ? '—' : `${attempt.responseTimeMs} ms`}</td><td>{attempt.payout == null ? '—' : formatMoney(attempt.payout)}</td></tr> })}</tbody></table></div> : <EmptyState title="No lead deliveries recorded" description="This lead has not entered a delivery sequence." />}</section><section className="panel"><div className="panel-heading"><div><h2>Rejections</h2><p>Structured outcome history</p></div></div>{rejections.length ? <div className="rejection-list">{rejections.map((item) => <article key={item.id}><XCircle size={17} /><div><strong>{item.category}</strong><p>{item.reason || item.rejectionCode}</p><small>{item.recoverable ? 'Recoverable' : 'Not currently recoverable'}</small></div></article>)}</div> : <EmptyState title="No rejection history" description="No buyer has rejected this lead." />}</section></div>
  </>
}

export function BuyerEcosystemPanels() {
  const { data, tenant } = useApp()
  const mappings = data.buyerPrograms.filter((item) => item.tenantId === tenant.id)
  const caps = data.buyerCaps.filter((item) => item.tenantId === tenant.id)
  return <div className="detail-grid registry-support"><section className="panel table-panel"><div className="panel-heading"><div><h2>Buyer-program eligibility</h2><p>Active program mappings and priority</p></div></div>{mappings.length ? <div className="table-scroll"><table><thead><tr><th>Buyer</th><th>Program</th><th>Payout</th><th>Priority</th><th>Status</th></tr></thead><tbody>{mappings.map((mapping) => <tr key={mapping.id}><td><Link className="text-button" to={`/buyers-offers/buyers/${mapping.buyerId}`}>{data.buyers.find((item) => item.id === mapping.buyerId)?.name}</Link></td><td>{data.programs.find((item) => item.id === mapping.programId)?.name}</td><td>{formatMoney(mapping.payout)}</td><td>{mapping.priority}</td><td><Status value={mapping.status} /></td></tr>)}</tbody></table></div> : <EmptyState title="No buyer-program mappings" description="Connect a buyer to its first eligible program." />}</section><section className="panel"><div className="panel-heading"><div><h2>Current buyer capacity</h2><p>Allocations without pacing recommendations</p></div></div>{caps.length ? <div className="capacity-list">{caps.map((cap) => { const used = percent(cap.delivered, cap.limit); return <article key={cap.id}><div><strong>{data.buyers.find((item) => item.id === cap.buyerId)?.name}</strong><small>{cap.capType} · {cap.limit - cap.delivered} remaining</small></div><b>{used}%</b><div className="capacity-track"><i style={{ width: `${used}%` }} /></div></article> })}</div> : <EmptyState title="No buyer caps configured" description="Add a capacity allocation when this tenant is ready." />}</section></div>
}

export function BuyerDetailPage() {
  const { buyerId } = useParams()
  const { data, tenant } = useApp()
  const { report } = useIntelligence()
  const buyer = data.buyers.find((item) => item.id === buyerId && item.tenantId === tenant.id)
  if (!buyer) return <Navigate to="/buyers-offers" replace />
  const mappings = data.buyerPrograms.filter((item) => item.buyerId === buyer.id)
  const caps = data.buyerCaps.filter((item) => item.buyerId === buyer.id)
  const attempts = data.deliveryAttempts.filter((item) => item.buyerId === buyer.id).slice(0, 8)
  const intelligence = report?.buyers.find((item) => item.buyerId === buyer.id)
  return <>
    <Link className="back-link" to="/buyers-offers"><ArrowLeft size={15} /> Back to Buyers & Offers</Link>
    <PageHeader eyebrow="Buyer operating profile" title={buyer.name} description="Eligibility, capacity, recent delivery activity, and tenant-scoped performance." action={<Status value={buyer.status} />} />
    <section className="panel"><dl className="buyer-summary"><div><dt>External ID</dt><dd className="mono">{buyer.externalReference || '—'}</dd></div><div><dt>Delivery</dt><dd>{buyer.deliveryMethod}</dd></div><div><dt>Default payout</dt><dd>{formatMoney(buyer.defaultPayout, buyer.currency)}</dd></div><div><dt>Exclusive</dt><dd>{buyer.exclusive ? 'Yes' : 'No'}</dd></div><div><dt>Duplicate window</dt><dd>{buyer.duplicateWindowDays} days</dd></div><div><dt>Timezone</dt><dd>{buyer.timezone}</dd></div></dl></section>
    <div className="detail-grid"><section className="panel"><div className="panel-heading"><div><h2>Programs</h2><p>Eligible operating relationships</p></div></div>{mappings.length ? <div className="simple-list">{mappings.map((mapping) => <div key={mapping.id}><div><strong>{data.programs.find((item) => item.id === mapping.programId)?.name}</strong><small>{formatMoney(mapping.payout)} · priority {mapping.priority}</small></div><Status value={mapping.status} /></div>)}</div> : <EmptyState title="No eligible programs" description="Connect this buyer to a program." />}</section><section className="panel"><div className="panel-heading"><div><h2>Caps</h2><p>Current allocation utilization</p></div></div>{caps.length ? <div className="capacity-list">{caps.map((cap) => { const used = percent(cap.delivered, cap.limit); return <article key={cap.id}><div><strong>{cap.capType} allocation</strong><small>{cap.delivered} delivered · {cap.limit - cap.delivered} remaining</small></div><b>{used}%</b><div className="capacity-track"><i style={{ width: `${used}%` }} /></div></article> })}</div> : <EmptyState title="No caps configured" description="This buyer has no active allocation." />}</section></div>
    <section className="panel table-panel"><div className="panel-heading"><div><h2>Recent delivery</h2><p>Operational attempts; no raw payloads stored</p></div></div>{attempts.length ? <div className="table-scroll"><table><thead><tr><th>Lead</th><th>Attempt</th><th>Status</th><th>Response</th><th>Created</th></tr></thead><tbody>{attempts.map((attempt) => <tr key={attempt.id}><td><Link className="text-button mono" to={`/leads/${attempt.leadId}`}>{data.leads.find((item) => item.id === attempt.leadId)?.reference}</Link></td><td>{attempt.attemptNumber}</td><td><Status value={attempt.status} /></td><td>{attempt.responseTimeMs == null ? '—' : `${attempt.responseTimeMs} ms`}</td><td>{formatDate(attempt.createdAt)}</td></tr>)}</tbody></table></div> : <EmptyState title="No delivery activity" description="No leads have been delivered to this buyer." />}</section>
    <section className="panel"><div className="panel-heading"><div><h2>Intelligence</h2><p>Performance in the active global intelligence period</p></div><Link className="text-button" to="/intelligence/buyers">Full scorecard <ArrowRight size={14} /></Link></div>{intelligence ? <dl className="buyer-summary"><div><dt>Attempted</dt><dd>{intelligence.attempted}</dd></div><div><dt>Accepted</dt><dd>{intelligence.accepted}</dd></div><div><dt>Rejected</dt><dd>{intelligence.rejected}</dd></div><div><dt>Acceptance rate</dt><dd>{intelligence.acceptanceRate == null ? '—' : `${intelligence.acceptanceRate}%`}</dd></div><div><dt>Average response</dt><dd>{intelligence.averageResponseMs == null ? '—' : `${intelligence.averageResponseMs} ms`}</dd></div><div><dt>Top rejection</dt><dd>{intelligence.topRejectionReason}</dd></div></dl> : <EmptyState title="No buyer intelligence for this period" description="Adjust the global filters or wait for delivery activity." />}</section>
  </>
}

export function RouteOperationsPage() {
  const { data, tenant } = useApp()
  const attempts = data.deliveryAttempts.filter((item) => item.tenantId === tenant.id)
  const caps = data.buyerCaps.filter((item) => item.tenantId === tenant.id)
  const ready = data.leads.filter((item) => item.tenantId === tenant.id && ['validated','queued'].includes(item.status)).length
  const summary = [
    { label: 'Ready for delivery', value: ready, icon: GitBranch },
    { label: 'Delivery attempts', value: attempts.length, icon: Send },
    { label: 'Accepted', value: attempts.filter((item) => item.status === 'accepted').length, icon: CheckCircle2 },
    { label: 'Rejected', value: attempts.filter((item) => item.status === 'rejected').length, icon: XCircle },
    { label: 'Timeouts / errors', value: attempts.filter((item) => ['timeout','error'].includes(item.status)).length, icon: AlertTriangle },
    { label: 'Buyer capacity', value: caps.reduce((total, cap) => total + Math.max(0, cap.limit - cap.delivered), 0), icon: Target },
  ]
  return <>
    <PageHeader eyebrow="Axis Route" title="Delivery operations" description="Monitor buyer interactions and capacity without automatic routing decisions." />
    <section className="route-stat-grid">{summary.map(({ icon: Icon, ...item }) => <article className="stat-card" key={item.label}><div className="stat-top"><span>{item.label}</span><Icon size={18} /></div><strong>{item.value}</strong><small>Operational snapshot</small></article>)}</section>
    <div className="detail-grid"><section className="panel table-panel"><div className="panel-heading"><div><h2>Recent attempts</h2><p>Ordered buyer delivery activity</p></div></div>{attempts.length ? <div className="table-scroll"><table><thead><tr><th>Lead</th><th>Buyer</th><th>#</th><th>Status</th><th>Response</th></tr></thead><tbody>{attempts.map((attempt) => <tr key={attempt.id}><td><Link className="text-button mono" to={`/leads/${attempt.leadId}`}>{data.leads.find((item) => item.id === attempt.leadId)?.reference}</Link></td><td>{data.buyers.find((item) => item.id === attempt.buyerId)?.name}</td><td>{attempt.attemptNumber}</td><td><Status value={attempt.status} /></td><td>{attempt.responseTimeMs == null ? 'Pending' : `${attempt.responseTimeMs} ms`}</td></tr>)}</tbody></table></div> : <EmptyState title="No lead deliveries recorded" description="Delivery activity will appear after a lead enters an operational sequence." />}</section><section className="panel"><div className="panel-heading"><div><h2>Capacity watch</h2><p>Current caps and remaining volume</p></div><Layers3 size={18} /></div>{caps.length ? <div className="capacity-list">{caps.map((cap) => { const used = percent(cap.delivered, cap.limit); return <article key={cap.id}><div><strong>{data.buyers.find((item) => item.id === cap.buyerId)?.name}</strong><small>{cap.delivered} / {cap.limit} · {cap.capType}</small></div><b>{cap.limit - cap.delivered}</b><div className="capacity-track"><i style={{ width: `${used}%` }} /></div></article> })}</div> : <EmptyState title="No buyer capacity configured" description="Buyer caps will appear here when allocations are added." />}</section></div>
    <div className="info-banner"><Clock3 size={18} /><div><strong>Routing execution is policy controlled</strong><span>Delivery history and capacity remain visible; execution is governed by Automation Center policies.</span></div></div>
  </>
}
